import {
  StartScreenElement,
  StartScreenConfig,
  generateDefaultStartScreenElements,
} from '../../../../games/shared/startScreenTypes';
import { GameTheme } from '../../../../themes/types';

export interface StartScreenPreset {
  id: string;
  name: string;
  description: string;
  category: 'arcade' | 'minimal' | 'tournament' | 'festival' | 'retro' | 'brand';
  elements: (theme?: Partial<GameTheme>, gameType?: string) => StartScreenElement[];
}

export const START_SCREEN_PRESETS: StartScreenPreset[] = [
  {
    id: 'arcade-showcase',
    name: 'Arcade Showcase (Default)',
    description: 'Balanced presentation with game emblem, title, subtitle, info badges, and glowing start button.',
    category: 'arcade',
    elements: (theme, gameType) => generateDefaultStartScreenElements({}, theme, gameType),
  },
  {
    id: 'sleek-dark-minimal',
    name: 'Sleek Dark Minimal',
    description: 'Clean, modern typography-focused layout on dark translucent glass with subtle borders.',
    category: 'minimal',
    elements: (theme, gameType) => [
      {
        id: 'card-minimal',
        type: 'card',
        x: 150,
        y: 220,
        width: 700,
        height: 520,
        rotation: 0,
        visible: true,
        opacity: 1,
        zIndex: 1,
        style: {
          backgroundColor: 'rgba(15, 23, 42, 0.85)',
          borderWidth: 1,
          borderColor: 'rgba(255, 255, 255, 0.1)',
          borderRadius: 32,
          shadow: true,
          backdropBlur: true,
        },
        children: [
          {
            id: 'title-minimal',
            type: 'title',
            x: 50,
            y: 70,
            width: 600,
            height: 80,
            rotation: 0,
            visible: true,
            opacity: 1,
            zIndex: 2,
            text: theme?.name || 'PLAY NOW',
            style: {
              fontSize: 44,
              fontWeight: '900',
              color: '#ffffff',
              textAlign: 'center',
              letterSpacing: 2,
            },
          },
          {
            id: 'desc-minimal',
            type: 'description',
            x: 70,
            y: 170,
            width: 560,
            height: 60,
            rotation: 0,
            visible: true,
            opacity: 1,
            zIndex: 2,
            text: theme?.description || 'Tap start to test your skills and reach the top of the leaderboard.',
            style: {
              fontSize: 16,
              fontWeight: 400,
              color: '#94a3b8',
              textAlign: 'center',
              lineHeight: 1.6,
            },
          },
          {
            id: 'btn-minimal',
            type: 'button',
            x: 120,
            y: 290,
            width: 460,
            height: 76,
            rotation: 0,
            visible: true,
            opacity: 1,
            zIndex: 3,
            text: 'LET\'S PLAY',
            action: 'startGame',
            iconName: 'play',
            style: {
              backgroundColor: '#38bdf8',
              textColor: '#0f172a',
              fontSize: 22,
              fontWeight: '900',
              borderRadius: 22,
              borderWidth: 0,
              shadow: true,
              pulse: true,
              letterSpacing: 1.5,
            },
          },
          {
            id: 'text-minimal-hint',
            type: 'text',
            x: 100,
            y: 400,
            width: 500,
            height: 30,
            rotation: 0,
            visible: true,
            opacity: 0.6,
            zIndex: 2,
            text: 'Press Space to start',
            style: {
              fontSize: 13,
              color: '#64748b',
              textAlign: 'center',
            },
          },
        ],
      },
    ],
  },
  {
    id: 'tournament-arena',
    name: 'Tournament Arena',
    description: 'Includes a live high-score leaderboard widget and competition rules directly on the start screen.',
    category: 'tournament',
    elements: (theme, gameType) => [
      {
        id: 'card-tournament',
        type: 'card',
        x: 100,
        y: 120,
        width: 800,
        height: 760,
        rotation: 0,
        visible: true,
        opacity: 1,
        zIndex: 1,
        style: {
          backgroundColor: 'rgba(10, 15, 30, 0.95)',
          borderWidth: 2,
          borderColor: '#f59e0b',
          borderRadius: 24,
          shadow: true,
          backdropBlur: true,
        },
        children: [
          {
            id: 'icon-trophy',
            type: 'icon',
            x: 360,
            y: 35,
            width: 80,
            height: 80,
            rotation: 0,
            visible: true,
            opacity: 1,
            zIndex: 2,
            iconName: 'Trophy',
            style: {
              backgroundColor: 'rgba(245, 158, 11, 0.2)',
              borderColor: '#f59e0b',
              borderWidth: 2,
              borderRadius: 24,
              iconColor: '#f59e0b',
              shadow: true,
            },
          },
          {
            id: 'title-tournament',
            type: 'title',
            x: 50,
            y: 125,
            width: 700,
            height: 60,
            rotation: 0,
            visible: true,
            opacity: 1,
            zIndex: 2,
            text: theme?.name || 'CHAMPIONSHIP ARENA',
            style: {
              fontSize: 36,
              fontWeight: '900',
              color: '#ffffff',
              textAlign: 'center',
              letterSpacing: 2,
            },
          },
          {
            id: 'leaderboard-tournament',
            type: 'leaderboard',
            x: 100,
            y: 200,
            width: 600,
            height: 180,
            rotation: 0,
            visible: true,
            opacity: 1,
            zIndex: 2,
            maxRows: 3,
            showHeader: true,
            headerText: 'CURRENT LEADERBOARD LEADERS',
            style: {
              backgroundColor: 'rgba(2, 6, 23, 0.85)',
              borderColor: '#334155',
              borderWidth: 1,
              borderRadius: 18,
            },
          },
          {
            id: 'rules-tournament',
            type: 'rules',
            x: 100,
            y: 400,
            width: 600,
            height: 120,
            rotation: 0,
            visible: true,
            opacity: 1,
            zIndex: 2,
            title: 'TOURNAMENT RULES',
            description: 'Fastest completion times and highest accuracy qualify for the prize pool!',
            style: {
              backgroundColor: 'rgba(2, 6, 23, 0.75)',
              borderColor: '#334155',
              borderWidth: 1,
              borderRadius: 18,
            },
          },
          {
            id: 'btn-tournament',
            type: 'button',
            x: 120,
            y: 550,
            width: 560,
            height: 76,
            rotation: 0,
            visible: true,
            opacity: 1,
            zIndex: 3,
            text: 'ENTER COMPETITION',
            action: 'startGame',
            iconName: 'play',
            style: {
              backgroundColor: '#f59e0b',
              textColor: '#020617',
              fontSize: 22,
              fontWeight: '900',
              borderRadius: 20,
              borderWidth: 0,
              shadow: true,
              pulse: true,
              letterSpacing: 1.5,
            },
          },
          {
            id: 'text-tournament-hint',
            type: 'text',
            x: 150,
            y: 650,
            width: 500,
            height: 30,
            rotation: 0,
            visible: true,
            opacity: 0.7,
            zIndex: 2,
            text: 'Authorized tournament session • Live score sync enabled',
            style: {
              fontSize: 12,
              color: '#94a3b8',
              textAlign: 'center',
            },
          },
        ],
      },
    ],
  },
  {
    id: 'vibrant-festival',
    name: 'Vibrant Festival',
    description: 'Festive carnival atmosphere with playful badges, colorful borders, and bold action callout.',
    category: 'festival',
    elements: (theme, gameType) => [
      {
        id: 'card-festival',
        type: 'card',
        x: 120,
        y: 160,
        width: 760,
        height: 640,
        rotation: 0,
        visible: true,
        opacity: 1,
        zIndex: 1,
        style: {
          backgroundColor: 'rgba(30, 20, 50, 0.95)',
          borderWidth: 2,
          borderColor: '#ec4899',
          borderRadius: 36,
          shadow: true,
          backdropBlur: true,
        },
        children: [
          {
            id: 'icon-festival',
            type: 'icon',
            x: 340,
            y: 40,
            width: 80,
            height: 80,
            rotation: 0,
            visible: true,
            opacity: 1,
            zIndex: 2,
            iconName: 'Sparkles',
            style: {
              backgroundColor: 'rgba(236, 72, 153, 0.2)',
              borderColor: '#ec4899',
              borderWidth: 2,
              borderRadius: 24,
              iconColor: '#f472b6',
              shadow: true,
            },
          },
          {
            id: 'title-festival',
            type: 'title',
            x: 40,
            y: 135,
            width: 680,
            height: 70,
            rotation: 0,
            visible: true,
            opacity: 1,
            zIndex: 2,
            text: theme?.name || 'CARNIVAL FUN',
            style: {
              fontSize: 40,
              fontWeight: '900',
              color: '#ffffff',
              textAlign: 'center',
              letterSpacing: 2,
            },
          },
          {
            id: 'desc-festival',
            type: 'description',
            x: 60,
            y: 215,
            width: 640,
            height: 60,
            rotation: 0,
            visible: true,
            opacity: 1,
            zIndex: 2,
            text: theme?.description || 'Step right up! Test your reflexes, win prizes, and enjoy the show!',
            style: {
              fontSize: 16,
              color: '#fbcfe8',
              textAlign: 'center',
            },
          },
          {
            id: 'badge-fest-1',
            type: 'badge',
            metric: 'grid',
            x: 140,
            y: 300,
            width: 220,
            height: 85,
            rotation: 0,
            visible: true,
            opacity: 1,
            zIndex: 2,
            label: 'GAME MODE',
            value: 'Speed Arcade',
            style: {
              backgroundColor: 'rgba(15, 10, 30, 0.85)',
              borderColor: '#a855f7',
              borderWidth: 1,
              borderRadius: 20,
              valueColor: '#c084fc',
            },
          },
          {
            id: 'badge-fest-2',
            type: 'badge',
            metric: 'timer',
            x: 400,
            y: 300,
            width: 220,
            height: 85,
            rotation: 0,
            visible: true,
            opacity: 1,
            zIndex: 2,
            label: 'TIME LIMIT',
            value: '45 Seconds',
            style: {
              backgroundColor: 'rgba(15, 10, 30, 0.85)',
              borderColor: '#ec4899',
              borderWidth: 1,
              borderRadius: 20,
              valueColor: '#f472b6',
            },
          },
          {
            id: 'btn-festival',
            type: 'button',
            x: 120,
            y: 430,
            width: 520,
            height: 80,
            rotation: 0,
            visible: true,
            opacity: 1,
            zIndex: 3,
            text: 'START CARNIVAL',
            action: 'startGame',
            iconName: 'play',
            style: {
              backgroundColor: '#ec4899',
              textColor: '#ffffff',
              fontSize: 24,
              fontWeight: '900',
              borderRadius: 24,
              borderWidth: 0,
              shadow: true,
              pulse: true,
              letterSpacing: 2,
            },
          },
        ],
      },
    ],
  },
  {
    id: 'retro-pixel',
    name: 'Retro 8-Bit Pixel',
    description: 'Nostalgic arcade machine styling with high-contrast borders and sharp typography.',
    category: 'retro',
    elements: (theme, gameType) => [
      {
        id: 'card-retro',
        type: 'card',
        x: 140,
        y: 180,
        width: 720,
        height: 600,
        rotation: 0,
        visible: true,
        opacity: 1,
        zIndex: 1,
        style: {
          backgroundColor: '#000000',
          borderWidth: 4,
          borderColor: '#22c55e',
          borderRadius: 8,
          shadow: true,
        },
        children: [
          {
            id: 'title-retro',
            type: 'title',
            x: 40,
            y: 50,
            width: 640,
            height: 70,
            rotation: 0,
            visible: true,
            opacity: 1,
            zIndex: 2,
            text: theme?.name || 'INSERT COIN',
            style: {
              fontSize: 40,
              fontWeight: '900',
              color: '#22c55e',
              textAlign: 'center',
              letterSpacing: 4,
            },
          },
          {
            id: 'desc-retro',
            type: 'description',
            x: 60,
            y: 140,
            width: 600,
            height: 50,
            rotation: 0,
            visible: true,
            opacity: 1,
            zIndex: 2,
            text: '1 PLAYER • P1 READY',
            style: {
              fontSize: 16,
              fontWeight: 700,
              color: '#86efac',
              textAlign: 'center',
              letterSpacing: 2,
            },
          },
          {
            id: 'rules-retro',
            type: 'rules',
            x: 80,
            y: 220,
            width: 560,
            height: 120,
            rotation: 0,
            visible: true,
            opacity: 1,
            zIndex: 2,
            title: 'ARCADE RULES',
            description: 'Match all targets before game over. Bonus score for streak combinations!',
            style: {
              backgroundColor: '#052e16',
              borderColor: '#22c55e',
              borderWidth: 2,
              borderRadius: 4,
              textColor: '#86efac',
            },
          },
          {
            id: 'btn-retro',
            type: 'button',
            x: 100,
            y: 380,
            width: 520,
            height: 76,
            rotation: 0,
            visible: true,
            opacity: 1,
            zIndex: 3,
            text: 'PRESS START',
            action: 'startGame',
            iconName: 'play',
            style: {
              backgroundColor: '#22c55e',
              textColor: '#000000',
              fontSize: 22,
              fontWeight: '900',
              borderRadius: 6,
              borderWidth: 0,
              shadow: true,
              pulse: true,
              letterSpacing: 2,
            },
          },
          {
            id: 'text-retro-credit',
            type: 'text',
            x: 110,
            y: 480,
            width: 500,
            height: 30,
            rotation: 0,
            visible: true,
            opacity: 1,
            zIndex: 2,
            text: 'CREDIT 01 • FREE PLAY',
            style: {
              fontSize: 14,
              fontWeight: 700,
              color: '#4ade80',
              textAlign: 'center',
              letterSpacing: 2,
            },
          },
        ],
      },
    ],
  },
  {
    id: 'brand-headline',
    name: 'Brand & Sponsor Headline',
    description: 'Prominent brand image placement, event title, sponsor subtitle, and sleek call to action.',
    category: 'brand',
    elements: (theme, gameType) => [
      {
        id: 'card-brand',
        type: 'card',
        x: 120,
        y: 150,
        width: 760,
        height: 660,
        rotation: 0,
        visible: true,
        opacity: 1,
        zIndex: 1,
        style: {
          backgroundColor: 'rgba(15, 23, 42, 0.95)',
          borderWidth: 1,
          borderColor: '#475569',
          borderRadius: 28,
          shadow: true,
          backdropBlur: true,
        },
        children: [
          {
            id: 'image-brand-logo',
            type: 'image',
            x: 230,
            y: 50,
            width: 300,
            height: 120,
            rotation: 0,
            visible: true,
            opacity: 1,
            zIndex: 2,
            imageUrl: theme?.clientLogo || theme?.logo || null,
            objectFit: 'contain',
          },
          {
            id: 'title-brand',
            type: 'title',
            x: 50,
            y: 190,
            width: 660,
            height: 70,
            rotation: 0,
            visible: true,
            opacity: 1,
            zIndex: 2,
            text: theme?.name || 'BRAND ACTIVATION',
            style: {
              fontSize: 38,
              fontWeight: '900',
              color: '#ffffff',
              textAlign: 'center',
              letterSpacing: 1.5,
            },
          },
          {
            id: 'desc-brand',
            type: 'description',
            x: 60,
            y: 270,
            width: 640,
            height: 60,
            rotation: 0,
            visible: true,
            opacity: 1,
            zIndex: 2,
            text: theme?.description || 'Welcome to the interactive brand booth experience! Tap start to play.',
            style: {
              fontSize: 16,
              color: '#94a3b8',
              textAlign: 'center',
            },
          },
          {
            id: 'btn-brand',
            type: 'button',
            x: 120,
            y: 380,
            width: 520,
            height: 76,
            rotation: 0,
            visible: true,
            opacity: 1,
            zIndex: 3,
            text: 'LAUNCH EXPERIENCE',
            action: 'startGame',
            iconName: 'play',
            style: {
              backgroundColor: '#f59e0b',
              textColor: '#0f172a',
              fontSize: 22,
              fontWeight: '900',
              borderRadius: 20,
              borderWidth: 0,
              shadow: true,
              pulse: true,
              letterSpacing: 1.5,
            },
          },
          {
            id: 'text-brand-footer',
            type: 'text',
            x: 100,
            y: 490,
            width: 560,
            height: 30,
            rotation: 0,
            visible: true,
            opacity: 0.7,
            zIndex: 2,
            text: 'Official Event Partner • All Rights Reserved',
            style: {
              fontSize: 12,
              color: '#64748b',
              textAlign: 'center',
            },
          },
        ],
      },
    ],
  },
];

export const instantiateStartPreset = (
  presetId: string,
  startConfig?: Partial<StartScreenConfig>,
  theme?: Partial<GameTheme>,
  gameType: string = 'memory-match'
): StartScreenElement[] => {
  const preset = START_SCREEN_PRESETS.find((p) => p.id === presetId);
  if (!preset) {
    return generateDefaultStartScreenElements(startConfig, theme, gameType);
  }
  return preset.elements(theme, gameType);
};
