import { GameTheme } from './types';
import { DEFAULT_GAME_LAYOUT } from './layout';

export const carnivalTheme: GameTheme = {
  id: 'carnival',
  base_theme_id: 'carnival',
  name: 'Carnival',
  slug: 'carnival',
  description: 'Grand festive celebration theme: Catch golden carnival tickets and cosmic stars while dodging cursed hazard masks.',
  status: 'active',

  branding: {
    gameTitle: 'CARNIVAL FIESTA',
    subtitle: 'Catch golden tickets, avoid cursed masks!',
    logoUrl: null,
    clientLogoUrl: null,
  },

  background_url: '/assets/themes/carnival/background.png',

  basket_config: {
    name: 'Carnival Cart',
    imageUrl: '/assets/themes/carnival/basket.png',
    width: 140,
    height: 70,
    catchAreaRatio: 0.75,
    speed: 550,
    collisionWidthRatio: 0.7235,
    collisionHeightRatio: 0.13,
    collisionOffsetYRatio: 0.3394,
  },

  items_config: [
    {
      id: 'ticket',
      name: 'Golden Carnival Ticket',
      imageUrl: '/assets/themes/carnival/item_normal_01.png',
      points: 10,
      speedMultiplier: 1.0,
      spawnWeight: 75,
      enabled: true,
      isHazard: false,
      isBonus: false,
      collisionRadiusRatio: 0.3,
      collisionCenterXRatio: 0.5,
      collisionCenterYRatio: 0.54,
    },
    {
      id: 'mask',
      name: 'Carnival Cursed Mask',
      imageUrl: '/assets/themes/carnival/item_hazard_01.png',
      points: -10,
      speedMultiplier: 1.15,
      spawnWeight: 20,
      enabled: true,
      isHazard: true,
      isBonus: false,
      collisionRadiusRatio: 0.3,
      collisionCenterXRatio: 0.5,
      collisionCenterYRatio: 0.54,
    },
    {
      id: 'star',
      name: 'Cosmic Carnival Star',
      imageUrl: '/assets/themes/carnival/item_bonus_01.png',
      points: 50,
      speedMultiplier: 1.3,
      spawnWeight: 5,
      enabled: true,
      isHazard: false,
      isBonus: true,
      collisionRadiusRatio: 0.3,
      collisionCenterXRatio: 0.5,
      collisionCenterYRatio: 0.54,
    },
  ],

  physics_config: {
    gameDurationSeconds: 20,
    baseFallSpeed: 500,
    fallSpeedMultiplier: 0.7,
    spawnIntervalMin: 550,
    spawnIntervalMax: 1000,
    difficultyStages: [
      {
        timeThreshold: 0,
        spawnInterval: 1000,
        speedMin: 350,
        speedMax: 500,
        hazardRatio: 0.2,
        bonusRatio: 0.05,
        stageName: 'Stage 1: Carnival Gates',
      },
      {
        timeThreshold: 7,
        spawnInterval: 750,
        speedMin: 400,
        speedMax: 600,
        hazardRatio: 0.3,
        bonusRatio: 0.08,
        stageName: 'Stage 2: Midway Magic',
      },
      {
        timeThreshold: 14,
        spawnInterval: 550,
        speedMin: 500,
        speedMax: 700,
        hazardRatio: 0.4,
        bonusRatio: 0.12,
        stageName: 'Stage 3: Grand Gala Storm!',
      },
    ],
  },

  visuals_config: {
    particleGood: 'particle_gold',
    particleBad: 'particle_spike',
    particleBonus: 'particle_star',
    primaryColor: '#f59e0b',
    secondaryColor: '#ec4899',
    accentColor: '#fbbf24',
    textColor: '#ffffff',
    cardGoodBg: 'rgba(180, 83, 9, 0.7)',
    cardGoodBorder: 'rgba(245, 158, 11, 0.5)',
    cardBadBg: 'rgba(159, 18, 57, 0.7)',
    cardBadBorder: 'rgba(244, 63, 94, 0.5)',
    bgGradientFrom: '#1e1035',
    bgGradientVia: '#18122B',
    bgGradientTo: '#0f172a',
  },

  sounds_config: {
    catchGoodUrl: null,
    catchBadUrl: null,
    catchBonusUrl: null,
    gameStartUrl: null,
    gameOverUrl: null,
    bgmUrl: null,
    soundVolume: 0.8,
    soundEnabled: true,
    bgmEnabled: true,
  },

  layout: DEFAULT_GAME_LAYOUT,

  // Backward compatibility fields
  background: '/assets/themes/carnival/background.png',
  catcher: '/assets/themes/carnival/basket.png',
  fallingObject: '/assets/themes/carnival/item_normal_01.png',
  badFallingObject: '/assets/themes/carnival/item_hazard_01.png',
  bonusFallingObject: '/assets/themes/carnival/item_bonus_01.png',
  gameTitle: 'CARNIVAL FIESTA',
  subtitle: 'Catch golden tickets, avoid cursed masks!',
  fallingObjectName: 'CARNIVAL TICKET',
  badFallingObjectName: 'CURSED MASK',
  bonusFallingObjectName: 'COSMIC STAR',
  catcherName: 'CARNIVAL CART',
  particles: {
    good: 'particle_gold',
    bad: 'particle_spike',
    bonus: 'particle_star',
  },
  colors: {
    primary: '#f59e0b',
    secondary: '#ec4899',
    accent: '#fbbf24',
    cardGoodBg: 'rgba(180, 83, 9, 0.7)',
    cardGoodBorder: 'rgba(245, 158, 11, 0.5)',
    cardBadBg: 'rgba(159, 18, 57, 0.7)',
    cardBadBorder: 'rgba(244, 63, 94, 0.5)',
  },
};
