import { GameTheme } from './types';
import { DEFAULT_GAME_LAYOUT } from './layout';

export const christmasTheme: GameTheme = {
  id: 'christmas',
  base_theme_id: 'christmas',
  name: 'Christmas',
  slug: 'christmas-rush',
  game_id: 'catch-brand',
  game_slug: 'catch-brand',
  game_type: 'catch-brand',
  game_name: 'Catch the Brand',
  description: 'Holiday festive arcade theme catching Christmas presents and avoiding naughty snowballs.',
  status: 'active',
  is_system: true,
  is_system_theme: true,
  ownership_type: 'system',

  branding: {
    gameTitle: 'CHRISTMAS GIFT RUSH',
    subtitle: 'Catch holiday presents, avoid naughty snowballs!',
    logoUrl: null,
    clientLogoUrl: null,
  },

  background_url: '/assets/games/catch-brand/themes/christmas/background.png',

  basket_config: {
    name: "Santa's Sack",
    imageUrl: '/assets/games/catch-brand/themes/christmas/basket.png',
    width: 140,
    height: 70,
    catchAreaRatio: 0.75,
    speed: 560,
    collisionWidthRatio: 0.75,
    collisionHeightRatio: 0.15,
    collisionOffsetYRatio: 0.32,
  },

  items_config: [
    {
      id: 'gift_box',
      name: 'Christmas Present',
      imageUrl: '/assets/games/catch-brand/themes/christmas/item_normal_01.png',
      points: 10,
      speedMultiplier: 1.0,
      spawnWeight: 75,
      enabled: true,
      isHazard: false,
      isBonus: false,
    },
    {
      id: 'coal_lump',
      name: 'Naughty Snowball',
      imageUrl: '/assets/games/catch-brand/themes/christmas/item_hazard_01.png',
      points: -10,
      speedMultiplier: 1.2,
      spawnWeight: 20,
      enabled: true,
      isHazard: true,
      isBonus: false,
    },
    {
      id: 'golden_star',
      name: 'Golden Star',
      imageUrl: '/assets/games/catch-brand/themes/christmas/item_bonus_01.png',
      points: 50,
      speedMultiplier: 1.35,
      spawnWeight: 5,
      enabled: true,
      isHazard: false,
      isBonus: true,
    },
  ],

  physics_config: {
    gameDurationSeconds: 20,
    baseFallSpeed: 500,
    fallSpeedMultiplier: 0.75,
    spawnIntervalMin: 500,
    spawnIntervalMax: 950,
    difficultyStages: [
      { timeThreshold: 0, spawnInterval: 950, speedMin: 350, speedMax: 500, hazardRatio: 0.2, bonusRatio: 0.05, stageName: 'Stage 1: Snow Flurry' },
      { timeThreshold: 7, spawnInterval: 700, speedMin: 420, speedMax: 620, hazardRatio: 0.3, bonusRatio: 0.08, stageName: 'Stage 2: Blizzard Rush' },
      { timeThreshold: 14, spawnInterval: 500, speedMin: 520, speedMax: 720, hazardRatio: 0.4, bonusRatio: 0.12, stageName: 'Stage 3: North Pole Storm!' },
    ],
  },

  visuals_config: {
    particleGood: 'particle_gold',
    particleBad: 'particle_spike',
    particleBonus: 'particle_gold',
    primaryColor: '#ef4444',
    secondaryColor: '#10b981',
    accentColor: '#fbbf24',
    textColor: '#ffffff',
    cardGoodBg: 'rgba(185, 28, 28, 0.7)',
    cardGoodBorder: 'rgba(239, 68, 68, 0.5)',
    cardBadBg: 'rgba(31, 41, 55, 0.7)',
    cardBadBorder: 'rgba(75, 85, 99, 0.5)',
    bgGradientFrom: '#0f172a',
    bgGradientTo: '#064e3b',
  },

  sounds_config: { soundVolume: 0.8, soundEnabled: true, bgmEnabled: true },
  layout: DEFAULT_GAME_LAYOUT,

  // Backward compatibility
  background: '/assets/games/catch-brand/themes/christmas/background.png',
  catcher: '/assets/games/catch-brand/themes/christmas/basket.png',
  fallingObject: '/assets/games/catch-brand/themes/christmas/item_normal_01.png',
  badFallingObject: '/assets/games/catch-brand/themes/christmas/item_hazard_01.png',
  bonusFallingObject: '/assets/games/catch-brand/themes/christmas/item_bonus_01.png',
  gameTitle: 'CHRISTMAS CATCH',
  subtitle: 'Catch falling Christmas gifts, avoid naughty snowballs!',
  fallingObjectName: 'GIFT BOX',
  badFallingObjectName: 'NAUGHTY SNOWBALL',
  bonusFallingObjectName: 'GOLDEN STAR',
  catcherName: 'SANTA SACK',
  particles: {
    good: 'particle_snowflake',
    bad: 'particle_soot',
    bonus: 'particle_star',
  },
  colors: {
    primary: '#ef4444',
    secondary: '#22c55e',
    accent: '#fef08a',
    cardGoodBg: 'rgba(20, 83, 45, 0.6)',
    cardGoodBorder: 'rgba(34, 197, 94, 0.4)',
    cardBadBg: 'rgba(127, 29, 29, 0.6)',
    cardBadBorder: 'rgba(239, 68, 68, 0.4)',
  },
};
