import { GameTheme } from './types';
import { DEFAULT_GAME_LAYOUT } from './layout';

export const defaultCatchBrandTheme: GameTheme = {
  id: 'default',
  base_theme_id: 'default',
  name: 'Default',
  slug: 'default',
  game_id: 'catch-brand',
  game_slug: 'catch-brand',
  game_type: 'catch-brand',
  game_name: 'Catch the Brand',
  description: 'Standard brand arcade theme: Catch good brand items and golden bonuses while dodging hazard obstacles.',
  status: 'active',
  is_default: true,
  is_system: true,
  is_system_theme: true,
  ownership_type: 'system',

  branding: {
    gameTitle: 'CATCH THE BRAND',
    subtitle: 'Catch good brand items, avoid hazards!',
    logoUrl: null,
    clientLogoUrl: null,
  },

  background_url: '/assets/games/catch-brand/themes/default/background.png',

  basket_config: {
    name: 'Basket',
    imageUrl: '/assets/games/catch-brand/themes/default/basket.png',
    width: 140,
    height: 70,
    catchAreaRatio: 0.75,
    speed: 550,
    collisionWidthRatio: 0.7235,
    collisionHeightRatio: 0.13,
    collisionOffsetYRatio: 0.3394,
  },

  items_config: [
    {
      id: 'item_normal_01',
      name: 'Brand Good Item',
      imageUrl: '/assets/games/catch-brand/themes/default/item_normal_01.png',
      points: 10,
      speedMultiplier: 1.0,
      spawnWeight: 75,
      enabled: true,
      isHazard: false,
      isBonus: false,
      collisionRadiusRatio: 0.3,
      collisionCenterXRatio: 0.5,
      collisionCenterYRatio: 0.54,
    },
    {
      id: 'item_hazard_01',
      name: 'Hazard Obstacle',
      imageUrl: '/assets/games/catch-brand/themes/default/item_hazard_01.png',
      points: -10,
      speedMultiplier: 1.15,
      spawnWeight: 20,
      enabled: true,
      isHazard: true,
      isBonus: false,
      collisionRadiusRatio: 0.3,
      collisionCenterXRatio: 0.5,
      collisionCenterYRatio: 0.54,
    },
    {
      id: 'item_bonus_01',
      name: 'Golden Bonus Item',
      imageUrl: '/assets/games/catch-brand/themes/default/item_bonus_01.png',
      points: 50,
      speedMultiplier: 1.3,
      spawnWeight: 5,
      enabled: true,
      isHazard: false,
      isBonus: true,
      collisionRadiusRatio: 0.3,
      collisionCenterXRatio: 0.5,
      collisionCenterYRatio: 0.54,
    },
  ],

  physics_config: {
    gameDurationSeconds: 20,
    baseFallSpeed: 500,
    fallSpeedMultiplier: 0.7,
    spawnIntervalMin: 550,
    spawnIntervalMax: 1000,
    difficultyStages: [
      {
        timeThreshold: 0,
        spawnInterval: 1000,
        speedMin: 350,
        speedMax: 500,
        hazardRatio: 0.2,
        bonusRatio: 0.05,
        stageName: 'Stage 1: Warm Up',
      },
      {
        timeThreshold: 7,
        spawnInterval: 750,
        speedMin: 400,
        speedMax: 600,
        hazardRatio: 0.3,
        bonusRatio: 0.08,
        stageName: 'Stage 2: Acceleration',
      },
      {
        timeThreshold: 14,
        spawnInterval: 550,
        speedMin: 500,
        speedMax: 700,
        hazardRatio: 0.4,
        bonusRatio: 0.12,
        stageName: 'Stage 3: Turbo Rush!',
      },
    ],
  },

  visuals_config: {
    particleGood: 'particle_gold',
    particleBad: 'particle_spike',
    particleBonus: 'particle_star',
    primaryColor: '#f59e0b',
    secondaryColor: '#ec4899',
    accentColor: '#fbbf24',
    textColor: '#ffffff',
    cardGoodBg: 'rgba(180, 83, 9, 0.7)',
    cardGoodBorder: 'rgba(245, 158, 11, 0.5)',
    cardBadBg: 'rgba(159, 18, 57, 0.7)',
    cardBadBorder: 'rgba(244, 63, 94, 0.5)',
    bgGradientFrom: '#1e1035',
    bgGradientVia: '#18122B',
    bgGradientTo: '#0f172a',
  },

  sounds_config: {
    catchGoodUrl: null,
    catchBadUrl: null,
    catchBonusUrl: null,
    gameStartUrl: null,
    gameOverUrl: null,
    bgmUrl: null,
    soundVolume: 0.8,
    soundEnabled: true,
    bgmEnabled: true,
  },

  layout: DEFAULT_GAME_LAYOUT,
};
