import { GameTheme } from './types';
import { DEFAULT_GAME_LAYOUT } from './layout';

export const durianTheme: GameTheme = {
  id: 'durian',
  base_theme_id: 'durian',
  name: 'Durian Catcher',
  slug: 'durian-catcher',
  description: 'Classic retro arcade game: Catch delicious green durians in a lush tropical forest.',
  status: 'active',
  is_active: true,

  branding: {
    gameTitle: 'DURIAN CATCHER',
    subtitle: 'Catch falling green durians, avoid spiky orange ones!',
    logoUrl: null,
    clientLogoUrl: null,
  },

  background_url: '/assets/background.png',

  basket_config: {
    name: 'Bamboo Basket',
    imageUrl: '/assets/basket.png',
    width: 140,
    height: 70,
    catchAreaRatio: 0.72,
    speed: 550,
    collisionWidthRatio: 0.7235,
    collisionHeightRatio: 0.13,
    collisionOffsetYRatio: 0.3394,
  },

  items_config: [
    {
      id: 'green_durian',
      name: 'Fresh Green Durian',
      imageUrl: '/assets/durian_green.png',
      points: 10,
      speedMultiplier: 1.0,
      spawnWeight: 75,
      enabled: true,
      isHazard: false,
      isBonus: false,
      collisionRadiusRatio: 0.3,
      collisionCenterXRatio: 0.5,
      collisionCenterYRatio: 0.54,
    },
    {
      id: 'orange_durian',
      name: 'Spiky Hazard Durian',
      imageUrl: '/assets/durian_brown.png',
      points: -10,
      speedMultiplier: 1.15,
      spawnWeight: 20,
      enabled: true,
      isHazard: true,
      isBonus: false,
      collisionRadiusRatio: 0.3,
      collisionCenterXRatio: 0.5,
      collisionCenterYRatio: 0.54,
    },
    {
      id: 'golden_durian',
      name: 'Golden Musang King',
      imageUrl: '/assets/durian_green.png',
      points: 50,
      speedMultiplier: 1.3,
      spawnWeight: 5,
      enabled: true,
      isHazard: false,
      isBonus: true,
      collisionRadiusRatio: 0.3,
      collisionCenterXRatio: 0.5,
      collisionCenterYRatio: 0.54,
    },
  ],

  physics_config: {
    gameDurationSeconds: 20,
    baseFallSpeed: 500,
    fallSpeedMultiplier: 0.7,
    spawnIntervalMin: 550,
    spawnIntervalMax: 1000,
    difficultyStages: [
      {
        timeThreshold: 0,
        spawnInterval: 1000,
        speedMin: 350,
        speedMax: 500,
        hazardRatio: 0.2,
        bonusRatio: 0.05,
        stageName: 'Stage 1: Calm Forest',
      },
      {
        timeThreshold: 7,
        spawnInterval: 750,
        speedMin: 400,
        speedMax: 600,
        hazardRatio: 0.3,
        bonusRatio: 0.08,
        stageName: 'Stage 2: Breezy Grove',
      },
      {
        timeThreshold: 14,
        spawnInterval: 550,
        speedMin: 500,
        speedMax: 700,
        hazardRatio: 0.4,
        bonusRatio: 0.12,
        stageName: 'Stage 3: Durian Storm!',
      },
    ],
  },

  visuals_config: {
    particleGood: 'particle_leaf',
    particleBad: 'particle_spike',
    particleBonus: 'particle_gold',
    primaryColor: '#10b981',
    secondaryColor: '#f59e0b',
    accentColor: '#ffee58',
    textColor: '#ffffff',
    cardGoodBg: 'rgba(6, 78, 59, 0.7)',
    cardGoodBorder: 'rgba(16, 185, 129, 0.5)',
    cardBadBg: 'rgba(136, 19, 55, 0.7)',
    cardBadBorder: 'rgba(244, 63, 94, 0.5)',
    bgGradientFrom: '#0a1d12',
    bgGradientVia: '#0c2012',
    bgGradientTo: '#102a18',
  },

  sounds_config: {
    catchGoodUrl: null,
    catchBadUrl: null,
    catchBonusUrl: null,
    gameStartUrl: null,
    gameOverUrl: null,
    bgmUrl: null,
    soundVolume: 0.8,
    soundEnabled: true,
    bgmEnabled: true,
  },

  layout: DEFAULT_GAME_LAYOUT,

  // Backward compatibility fields
  background: '/assets/background.png',
  catcher: '/assets/basket.png',
  fallingObject: '/assets/durian_green.png',
  badFallingObject: '/assets/durian_brown.png',
  bonusFallingObject: '/assets/durian_green.png',
  gameTitle: 'DURIAN CATCHER',
  subtitle: 'Catch falling green durians, avoid spiky orange ones!',
  fallingObjectName: 'GREEN DURIAN',
  badFallingObjectName: 'ORANGE DURIAN',
  bonusFallingObjectName: 'GOLDEN DURIAN',
  catcherName: 'BASKET',
  particles: {
    good: 'particle_leaf',
    bad: 'particle_spike',
    bonus: 'particle_gold',
  },
  colors: {
    primary: '#10b981',
    secondary: '#f59e0b',
    accent: '#ffee58',
    cardGoodBg: 'rgba(6, 78, 59, 0.6)',
    cardGoodBorder: 'rgba(16, 185, 129, 0.4)',
    cardBadBg: 'rgba(136, 19, 55, 0.6)',
    cardBadBorder: 'rgba(244, 63, 94, 0.4)',
  },
};
