import { GameTheme } from './types';
import { DEFAULT_GAME_LAYOUT } from './layout';

export const memoryMatchTheme: GameTheme = {
  id: 'memory-carnival',
  base_theme_id: 'memory-carnival',
  name: 'Memory Carnival Pairs',
  slug: 'memory-carnival',
  game_id: 'memory-match',
  game_slug: 'memory-match',
  game_type: 'memory-match',
  game_name: 'Brand Memory Match',
  description: 'Classic memory concentration card match with 8 carnival attraction pairs, time bonuses, and combo multipliers.',
  status: 'active',
  is_default: true,
  is_system: true,
  ownership_type: 'system',

  branding: {
    gameTitle: 'MEMORY MATCH CARNIVAL',
    subtitle: 'Flip cards, match 8 carnival pairs, and beat the clock!',
    logoUrl: null,
    clientLogoUrl: null,
  },

  background_url: '/assets/themes/carnival/background.png',

  basket_config: {
    name: 'Card Deck',
    imageUrl: null,
    width: 140,
    height: 70,
    catchAreaRatio: 0.75,
    speed: 550,
  },

  items_config: [
    {
      id: 'pair_ticket',
      name: 'Golden Ticket',
      imageUrl: '/assets/themes/carnival/item_normal_01.png',
      points: 100,
      speedMultiplier: 1.0,
      spawnWeight: 12,
      enabled: true,
      isHazard: false,
      isBonus: false,
    },
    {
      id: 'pair_mask',
      name: 'Carnival Mask',
      imageUrl: '/assets/themes/carnival/item_hazard_01.png',
      points: 100,
      speedMultiplier: 1.0,
      spawnWeight: 12,
      enabled: true,
      isHazard: false,
      isBonus: false,
    },
    {
      id: 'pair_star',
      name: 'Cosmic Star',
      imageUrl: '/assets/themes/carnival/item_bonus_01.png',
      points: 100,
      speedMultiplier: 1.0,
      spawnWeight: 12,
      enabled: true,
      isHazard: false,
      isBonus: true,
    },
    {
      id: 'pair_cart',
      name: 'Carnival Cart',
      imageUrl: '/assets/themes/carnival/basket.png',
      points: 100,
      speedMultiplier: 1.0,
      spawnWeight: 12,
      enabled: true,
      isHazard: false,
      isBonus: false,
    },
    {
      id: 'pair_tent',
      name: 'Big Top Tent',
      imageUrl: null,
      points: 100,
      speedMultiplier: 1.0,
      spawnWeight: 12,
      enabled: true,
      isHazard: false,
      isBonus: false,
    },
    {
      id: 'pair_balloons',
      name: 'Party Balloons',
      imageUrl: null,
      points: 100,
      speedMultiplier: 1.0,
      spawnWeight: 12,
      enabled: true,
      isHazard: false,
      isBonus: false,
    },
    {
      id: 'pair_cup',
      name: 'Carnival Cup',
      imageUrl: null,
      points: 100,
      speedMultiplier: 1.0,
      spawnWeight: 12,
      enabled: true,
      isHazard: false,
      isBonus: false,
    },
    {
      id: 'pair_wheel',
      name: 'Fortune Wheel',
      imageUrl: null,
      points: 100,
      speedMultiplier: 1.0,
      spawnWeight: 12,
      enabled: true,
      isHazard: false,
      isBonus: false,
    },
  ],

  physics_config: {
    gameDurationSeconds: 45,
    baseFallSpeed: 500,
    fallSpeedMultiplier: 1.0,
    spawnIntervalMin: 500,
    spawnIntervalMax: 1000,
    difficultyStages: [
      {
        timeThreshold: 0,
        spawnInterval: 1000,
        speedMin: 350,
        speedMax: 500,
        hazardRatio: 0,
        bonusRatio: 0,
        stageName: 'Classic 4x4 Grid',
      },
    ],
  },

  visuals_config: {
    particleGood: 'particle_gold',
    particleBad: 'particle_spike',
    particleBonus: 'particle_star',
    primaryColor: '#f59e0b',
    secondaryColor: '#ec4899',
    accentColor: '#10b981',
    textColor: '#ffffff',
    cardGoodBg: 'rgba(6, 78, 59, 0.85)',
    cardGoodBorder: '#10b981',
    cardBadBg: 'rgba(15, 23, 42, 0.95)',
    cardBadBorder: '#f59e0b',
    bgGradientFrom: '#0f172a',
    bgGradientVia: '#1e1b4b',
    bgGradientTo: '#0f172a',
  },

  sounds_config: {
    soundVolume: 0.8,
    soundEnabled: true,
    bgmEnabled: true,
  },

  layout: DEFAULT_GAME_LAYOUT,
};
