import { GameTheme, DEFAULT_MEMORY_MATCH_CONFIG } from './types';
import { DEFAULT_MEMORY_MATCH_LAYOUT } from './layout';

export const memoryMatchTheme: GameTheme = {
  id: 'memory-match',
  base_theme_id: 'memory-match',
  name: 'Brand Memory Match',
  slug: 'memory-match',
  game_id: 'c782cc78-d2f6-4e70-ac90-bbf9824c62f9',
  game_slug: 'memory-match',
  game_type: 'memory-match',
  game_name: 'Brand Memory Match',
  description: 'Classic memory concentration card match with 8 pairs, time bonuses, and combo multipliers.',
  status: 'active',
  is_default: true,
  is_system: true,
  ownership_type: 'system',

  branding: {
    gameTitle: 'BRAND MEMORY MATCH',
    subtitle: 'Flip cards, match 8 pairs, and beat the clock!',
    logoUrl: null,
    clientLogoUrl: null,
  },

  background_url: '',

  basket_config: null,

  game_config: DEFAULT_MEMORY_MATCH_CONFIG,

  items_config: [

    {
      id: 'pair_diamond',
      name: 'Diamond',
      imageUrl: null,
      points: 100,
      speedMultiplier: 1.0,
      spawnWeight: 1,
      enabled: true,
      isHazard: false,
      isBonus: false,
    },
    {
      id: 'pair_crown',
      name: 'Crown',
      imageUrl: null,
      points: 100,
      speedMultiplier: 1.0,
      spawnWeight: 1,
      enabled: true,
      isHazard: false,
      isBonus: false,
    },
    {
      id: 'pair_star',
      name: 'Star',
      imageUrl: null,
      points: 100,
      speedMultiplier: 1.0,
      spawnWeight: 1,
      enabled: true,
      isHazard: false,
      isBonus: false,
    },
    {
      id: 'pair_heart',
      name: 'Heart',
      imageUrl: null,
      points: 100,
      speedMultiplier: 1.0,
      spawnWeight: 1,
      enabled: true,
      isHazard: false,
      isBonus: false,
    },
    {
      id: 'pair_lightning',
      name: 'Lightning',
      imageUrl: null,
      points: 100,
      speedMultiplier: 1.0,
      spawnWeight: 1,
      enabled: true,
      isHazard: false,
      isBonus: false,
    },
    {
      id: 'pair_shield',
      name: 'Shield',
      imageUrl: null,
      points: 100,
      speedMultiplier: 1.0,
      spawnWeight: 1,
      enabled: true,
      isHazard: false,
      isBonus: false,
    },
    {
      id: 'pair_trophy',
      name: 'Trophy',
      imageUrl: null,
      points: 100,
      speedMultiplier: 1.0,
      spawnWeight: 1,
      enabled: true,
      isHazard: false,
      isBonus: false,
    },
    {
      id: 'pair_rocket',
      name: 'Rocket',
      imageUrl: null,
      points: 100,
      speedMultiplier: 1.0,
      spawnWeight: 1,
      enabled: true,
      isHazard: false,
      isBonus: false,
    },
  ],

  physics_config: {
    gameDurationSeconds: 45,
    baseFallSpeed: 0,
    fallSpeedMultiplier: 1.0,
    spawnIntervalMin: 0,
    spawnIntervalMax: 0,
    difficultyStages: [],
  },

  visuals_config: {
    cardBackUrl: null,
    cardFrontBg: '#0f172a',
    cardFrontBgOpacity: 0.95,
    particleGood: 'particle_gold',
    particleBad: 'particle_spike',
    particleBonus: 'particle_star',
    primaryColor: '#6366f1',
    secondaryColor: '#ec4899',
    accentColor: '#10b981',
    textColor: '#ffffff',
    cardGoodBg: '#064E3B',
    cardGoodBgOpacity: 0.85,
    cardGoodBorder: '#10b981',
    cardBadBg: 'rgba(15, 23, 42, 0.95)',
    cardBadBorder: '#334155',
    bgGradientFrom: '#0f172a',
    bgGradientVia: '#1e1b4b',
    bgGradientTo: '#0f172a',
  },

  sounds_config: {
    soundVolume: 0.8,
    soundEnabled: true,
    bgmEnabled: true,
  },

  layout: DEFAULT_MEMORY_MATCH_LAYOUT,
};
