import fs from 'fs';
import path from 'path';

const enPath = path.resolve('src/locales/en.ts');
const zhPath = path.resolve('src/locales/zh-CN.ts');
const msPath = path.resolve('src/locales/ms-MY.ts');

const newTranslations = {
  common: {
    en: {
      browseFiles: 'Browse Files',
      available: 'Available',
      restart: 'Restart',
      exitFullscreen: 'Exit Fullscreen',
      fullscreen: 'Toggle Fullscreen',
      draft: 'Drafts Only',
      archived: 'Archived',
      allStatus: 'All Status',
    },
    zh: {
      browseFiles: '浏览文件',
      available: '可用',
      restart: '重新开始',
      exitFullscreen: '退出全屏',
      fullscreen: '切换全屏',
      draft: '仅草稿',
      archived: '已归档',
      allStatus: '全部状态',
    },
    ms: {
      browseFiles: 'Semak Imbas Fail',
      available: 'Tersedia',
      restart: 'Mulakan Semula',
      exitFullscreen: 'Keluar Skrin Penuh',
      fullscreen: 'Togol Skrin Penuh',
      draft: 'Draf Sahaja',
      archived: 'Diarkibkan',
      allStatus: 'Semua Status',
    },
  },
  event: {
    en: {
      retrievingDeployments: 'Retrieving your event deployments. This may take a moment.',
      namePlaceholder: 'e.g. ABC Company Annual Summit 2026',
      dateRangeInvalid: 'The event end date cannot be earlier than the start date. Please select a valid date range.',
      evaluatesTimezone: 'Evaluates setup day & midnight cutoffs',
      instantUrlCreation: 'Instant URL Creation',
      instantUrlCreationDesc: 'Your event will be created and receive its permanent URL immediately. You can test and inspect the game before completing payment & activation.',
      ownerTesterOnly: 'Owner & Tester Access Only',
      publicUrlAfterPayment: 'Public player link is generated ONLY after payment confirmation',
      publicUrlAfterPaymentDesc: 'You can test gameplay and verify theme configurations via the preview link above. To publish the event to the public and start live leaderboard scoring, proceed to payment and activation.',
      paymentConfirmedLive: 'Payment confirmed. Your event is now LIVE and the public player URL is ready.',
    },
    zh: {
      retrievingDeployments: '正在获取您的活动部署，请稍候。',
      namePlaceholder: '例如：ABC 企业 2026 年度盛典',
      dateRangeInvalid: '活动结束日期不能早于开始日期，请选择有效的日期范围。',
      evaluatesTimezone: '用于计算布展日与午夜截止时间',
      instantUrlCreation: '即时生成活动链接',
      instantUrlCreationDesc: '活动创建后将立即获得专属链接。您可以在完成付款与激活之前随时测试与查看游戏。',
      ownerTesterOnly: '仅限机构所有者与测试人员访问',
      publicUrlAfterPayment: '公开玩家链接仅在确认付款后生成',
      publicUrlAfterPaymentDesc: '您可以通过上方的预览链接测试玩法并确认主题。如需向公众发布活动并开启实时排行榜计分，请继续前往付款与激活。',
      paymentConfirmedLive: '付款已确认。您的活动现已上线，公开玩家 URL 已就绪。',
    },
    ms: {
      retrievingDeployments: 'Sedang mendapatkan pelaksanaan acara anda. Ini mungkin mengambil masa sebentar.',
      namePlaceholder: 'cth. Sidang Kemuncak Tahunan Syarikat ABC 2026',
      dateRangeInvalid: 'Tarikh tamat acara tidak boleh lebih awal daripada tarikh mula. Sila pilih julat tarikh yang sah.',
      evaluatesTimezone: 'Menilai hari persediaan & had tengah malam',
      instantUrlCreation: 'Penciptaan URL Serta-merta',
      instantUrlCreationDesc: 'Acara anda akan dicipta dan menerima URL kekal serta-merta. Anda boleh menguji dan memeriksa permainan sebelum melengkapkan pembayaran & pengaktifan.',
      ownerTesterOnly: 'Akses Pemilik & Penguji Sahaja',
      publicUrlAfterPayment: 'Pautan pemain awam dijana HANYA selepas pengesahan pembayaran',
      publicUrlAfterPaymentDesc: 'Anda boleh menguji cara permainan dan mengesahkan konfigurasi tema melalui pautan pratonton di atas. Untuk menerbitkan acara kepada umum dan memulakan skor papan pendahulu secara langsung, teruskan ke pembayaran dan pengaktifan.',
      paymentConfirmedLive: 'Pembayaran disahkan. Acara anda kini LANGSUNG dan URL pemain awam sedia digunakan.',
    },
  },
  payment: {
    en: {
      selectCreditsNotice: 'Select the credits you want to use for this event.',
      appliedToPrice: 'Applied to price',
      clickToApply: 'Click to apply',
      refreshBalances: 'Refresh Wallet Balances and Ledger',
      standardEventPrice: 'Standard Event Price:',
      paidBalance: 'Paid Balance',
      topUpCredit: 'Top-up Credit',
      welcomeCredit: 'Welcome Credit',
      showcaseCredit: 'Showcase Credit',
      searchLedgerPlaceholder: 'Search description, reference, ID...',
      customRange: 'Custom Range',
      startDate: 'Start:',
      endDate: 'End:',
      clearFilters: 'Clear Filters',
      loadingLedger: 'Loading transaction ledger...',
      noTransactionsFound: 'No Transactions Found',
      balanceImpact: 'Balance Impact',
      reference: 'Reference',
      copyReference: 'Copy Reference',
      immutableLedger: 'Immutable Ledger Protection',
      walletRules: 'Wallet Rules & Credit Terms',
      fullCancellationRefunds: 'Full Cancellation Refunds',
      promotionalCreditPriority: 'Promotional Credit Priority',
      earnShowcaseRewards: 'Earn Showcase Rewards',
      topUpDetail: 'Top Up Detail',
      topUpDetailDesc: 'Order breakdown and wallet credit summary',
      depositedToPaidBalance: 'Deposited to Paid Balance',
      promotionalBonusValue: 'Promotional bonus value',
      totalWalletValue: 'Total Wallet Value',
      totalSpendingPower: 'Total spending power added',
      paymentReference: 'Payment Reference',
      copyPaymentReference: 'Copy Payment Reference',
      topUpOrder: 'Top Up Order',
      copyOrderId: 'Copy Order ID',
      transactionAuditRecord: 'Transaction Audit Record',
      timestamp: 'Timestamp',
      ledgerDescription: 'Ledger Description',
      securePaymentCheckout: 'Secure Payment Checkout',
      totalDue: 'Total Due',
      topUpDeposit: 'Top-Up Deposit',
      paymentMethod: 'Payment Method',
      creditOrDebit: 'Credit / Debit Card',
      cardBrands: 'Visa, Mastercard, American Express',
      verifyingSimulation: 'Verifying Simulation...',
      simulateSucceeded: 'Simulate Webhook: Succeeded',
      simulateExpired: 'Simulate: Expired',
      simulateFailed: 'Simulate: Failed',
      webhookPending: 'Payment Gateway Returned • Webhook Pending',
      confirmationPending: 'Payment Confirmation Pending',
      promotionalTopUpCredit: 'Promotional Top-up Credit',
      totalValueToCredit: 'Total Value to Credit',
      realTimeStatusCheck: 'Real-Time Status Check',
      secondsWindow: '10–30 seconds',
      checkPaymentStatusNow: 'Check Payment Status Now',
      developerTestingSandbox: 'Developer Testing Sandbox (Late Webhook Scenario)',
      simulate15sDelay: 'Simulate 15s Delay',
      simulateArrivedNow: 'Simulate Arrived Now',
      walletValueAdded: 'Wallet Value Added',
      orderReference: 'Order Reference',
      ledgerVerification: 'Ledger Verification',
      topUpExpired: 'Top-up Expired',
      topUpExpiredDesc: 'Top-up expired. Please create a new top-up.',
      attemptedAmount: 'Attempted Amount',
      createNewTopUp: 'Create New Top-up',
      topUpCancelled: 'Top-up Cancelled',
      topUpCancelledDesc: 'Top-up was cancelled. No charges were made.',
      startNewTopUp: 'Start New Top-up',
      paymentFailedDesc: 'Payment could not be completed.',
      tryAgain: 'Try Again',
      organizationWallet: 'Organization Wallet',
      backToWalletOverview: 'Back to Wallet Overview',
      topUpWallet: 'Top Up Wallet',
      currentUsableBalance: 'Current Usable Balance',
      selectTopUpAmount: 'Select Top Up Amount',
      minTopUp: 'Min: RM 1.00',
      amountPlaceholder: 'e.g. 7500.00',
      walletBalancePoolsPolicy: 'Wallet Balance Pools & Policy',
      orderSummary: 'Order Summary',
      selectedAmount: 'Selected Amount',
      purchasedFundsPromo: 'Purchased funds + Promotional bonus',
      youPay: 'You Pay',
      walletValueAfterTopUp: 'Wallet Value After Top Up',
      connectingPaymentGateway: 'Connecting to Payment Gateway...',
      continueToPayment: 'Continue to Payment',
      encryptedPaymentNotice: '256-bit Encrypted Payment Gateway • Webhook Verified',
    },
    zh: {
      selectCreditsNotice: '选择您希望在本次活动中抵扣的积分。',
      appliedToPrice: '已抵扣金额',
      clickToApply: '点击抵扣',
      refreshBalances: '刷新钱包余额与账目明细',
      standardEventPrice: '标准活动定价：',
      paidBalance: '充值现金余额',
      topUpCredit: '充值奖励积分',
      welcomeCredit: '新人首单迎新积分',
      showcaseCredit: '活动案例展示奖励积分',
      searchLedgerPlaceholder: '搜索交易描述、参考号、订单号...',
      customRange: '自定义日期范围',
      startDate: '开始：',
      endDate: '结束：',
      clearFilters: '清除筛选',
      loadingLedger: '正在加载交易账目...',
      noTransactionsFound: '未找到任何交易记录',
      balanceImpact: '余额变动',
      reference: '参考号',
      copyReference: '复制参考号',
      immutableLedger: '不可篡改账目保护',
      walletRules: '钱包规则与积分条款',
      fullCancellationRefunds: '取消活动全额退款',
      promotionalCreditPriority: '优先使用优惠积分',
      earnShowcaseRewards: '发布活动展示赢取奖励',
      topUpDetail: '充值详情',
      topUpDetailDesc: '订单费用明细与钱包积分汇总',
      depositedToPaidBalance: '存入现金账户',
      promotionalBonusValue: '充值奖励赠送价值',
      totalWalletValue: '钱包总可用价值',
      totalSpendingPower: '增加的总消费额度',
      paymentReference: '支付参考号',
      copyPaymentReference: '复制支付参考号',
      topUpOrder: '充值订单',
      copyOrderId: '复制订单编号',
      transactionAuditRecord: '交易审计记录',
      timestamp: '时间戳',
      ledgerDescription: '账本描述',
      securePaymentCheckout: '安全收银台结账',
      totalDue: '应付金额',
      topUpDeposit: '充值存款',
      paymentMethod: '支付方式',
      creditOrDebit: '信用卡 / 借记卡',
      cardBrands: 'Visa, Mastercard, American Express',
      verifyingSimulation: '正在验证仿真...',
      simulateSucceeded: '模拟 Webhook：支付成功',
      simulateExpired: '模拟：订单已过期',
      simulateFailed: '模拟：支付失败',
      webhookPending: '支付网关已返回 • 正在等待 Webhook 回调',
      confirmationPending: '支付确认处理中',
      promotionalTopUpCredit: '充值优惠赠送积分',
      totalValueToCredit: '入账总价值',
      realTimeStatusCheck: '实时状态检查',
      secondsWindow: '10–30 秒',
      checkPaymentStatusNow: '立即检查支付状态',
      developerTestingSandbox: '开发者测试沙盒（延时 Webhook 测试）',
      simulate15sDelay: '模拟延迟 15 秒',
      simulateArrivedNow: '模拟立即到达',
      walletValueAdded: '已增加的钱包价值',
      orderReference: '订单参考号',
      ledgerVerification: '账目核验',
      topUpExpired: '充值已超时',
      topUpExpiredDesc: '充值订单已过期，请发起新的充值。',
      attemptedAmount: '发起充值金额',
      createNewTopUp: '新建充值订单',
      topUpCancelled: '充值已取消',
      topUpCancelledDesc: '充值订单已取消，未产生任何扣费。',
      startNewTopUp: '重新发起充值',
      paymentFailedDesc: '支付未能成功完成。',
      tryAgain: '重试',
      organizationWallet: '机构钱包',
      backToWalletOverview: '返回钱包概览',
      topUpWallet: '钱包充值',
      currentUsableBalance: '当前可用余额总计',
      selectTopUpAmount: '选择充值金额',
      minTopUp: '最低充值：RM 1.00',
      amountPlaceholder: '例如：7500.00',
      walletBalancePoolsPolicy: '钱包账户资金池与使用规则',
      orderSummary: '订单摘要',
      selectedAmount: '已选充值金额',
      purchasedFundsPromo: '充值本金 + 赠送积分',
      youPay: '实际支付',
      walletValueAfterTopUp: '充值后钱包总价值',
      connectingPaymentGateway: '正在连接支付网关...',
      continueToPayment: '继续前往支付',
      encryptedPaymentNotice: '256 位加密安全支付网关 • Webhook 签名验证',
    },
    ms: {
      selectCreditsNotice: 'Pilih kredit yang ingin anda gunakan untuk acara ini.',
      appliedToPrice: 'Ditolak daripada harga',
      clickToApply: 'Klik untuk guna',
      refreshBalances: 'Segarkan Baki Dompet & Lejar',
      standardEventPrice: 'Harga Acara Standard:',
      paidBalance: 'Baki Berbayar',
      topUpCredit: 'Kredit Tambah Nilai',
      welcomeCredit: 'Kredit Selamat Datang',
      showcaseCredit: 'Kredit Pameran',
      searchLedgerPlaceholder: 'Cari penerangan, rujukan, ID...',
      customRange: 'Julat Tersuai',
      startDate: 'Mula:',
      endDate: 'Tamat:',
      clearFilters: 'Kosongkan Penapis',
      loadingLedger: 'Sedang memuatkan lejar transaksi...',
      noTransactionsFound: 'Tiada Transaksi Ditemui',
      balanceImpact: 'Kesan Baki',
      reference: 'Rujukan',
      copyReference: 'Salin Rujukan',
      immutableLedger: 'Perlindungan Lejar Tidak Boleh Diubah',
      walletRules: 'Peraturan Dompet & Syarat Kredit',
      fullCancellationRefunds: 'Bayaran Balik Penuh Pembatalan',
      promotionalCreditPriority: 'Keutamaan Kredit Promosi',
      earnShowcaseRewards: 'Dapatkan Ganjaran Pameran',
      topUpDetail: 'Butiran Tambah Nilai',
      topUpDetailDesc: 'Pecahan pesanan dan ringkasan kredit dompet',
      depositedToPaidBalance: 'Dimasukkan ke Baki Berbayar',
      promotionalBonusValue: 'Nilai bonus promosi',
      totalWalletValue: 'Jumlah Nilai Dompet',
      totalSpendingPower: 'Jumlah kuasa perbelanjaan ditambah',
      paymentReference: 'Rujukan Pembayaran',
      copyPaymentReference: 'Salin Rujukan Pembayaran',
      topUpOrder: 'Pesanan Tambah Nilai',
      copyOrderId: 'Salin ID Pesanan',
      transactionAuditRecord: 'Rekod Audit Transaksi',
      timestamp: 'Cap Masa',
      ledgerDescription: 'Penerangan Lejar',
      securePaymentCheckout: 'Daftar Keluar Pembayaran Selamat',
      totalDue: 'Jumlah Perlu Dibayar',
      topUpDeposit: 'Deposit Tambah Nilai',
      paymentMethod: 'Kaedah Pembayaran',
      creditOrDebit: 'Kad Kredit / Debit',
      cardBrands: 'Visa, Mastercard, American Express',
      verifyingSimulation: 'Mengesahkan Simulasi...',
      simulateSucceeded: 'Simulasi Webhook: Berjaya',
      simulateExpired: 'Simulasi: Tamat Tempoh',
      simulateFailed: 'Simulasi: Gagal',
      webhookPending: 'Pintu Masuk Pembayaran Dikembalikan • Menunggu Webhook',
      confirmationPending: 'Pengesahan Pembayaran Sedang Diproses',
      promotionalTopUpCredit: 'Kredit Tambah Nilai Promosi',
      totalValueToCredit: 'Jumlah Nilai untuk Dikreditkan',
      realTimeStatusCheck: 'Semakan Status Masa Nyata',
      secondsWindow: '10–30 saat',
      checkPaymentStatusNow: 'Semak Status Pembayaran Sekarang',
      developerTestingSandbox: 'Kotak Pasir Ujian Pembangun (Senario Webhook Lewat)',
      simulate15sDelay: 'Simulasikan Kelewatan 15s',
      simulateArrivedNow: 'Simulasikan Sampai Sekarang',
      walletValueAdded: 'Nilai Dompet Ditambah',
      orderReference: 'Rujukan Pesanan',
      ledgerVerification: 'Pengesahan Lejar',
      topUpExpired: 'Tambah Nilai Tamat Tempoh',
      topUpExpiredDesc: 'Tambah nilai tamat tempoh. Sila buat tambah nilai baharu.',
      attemptedAmount: 'Jumlah Dicuba',
      createNewTopUp: 'Cipta Tambah Nilai Baharu',
      topUpCancelled: 'Tambah Nilai Dibatalkan',
      topUpCancelledDesc: 'Tambah nilai telah dibatalkan. Tiada caj dikenakan.',
      startNewTopUp: 'Mulakan Tambah Nilai Baharu',
      paymentFailedDesc: 'Pembayaran tidak dapat diselesaikan.',
      tryAgain: 'Cuba Lagi',
      organizationWallet: 'Dompet Organisasi',
      backToWalletOverview: 'Kembali ke Gambaran Keseluruhan Dompet',
      topUpWallet: 'Tambah Nilai Dompet',
      currentUsableBalance: 'Jumlah Baki Boleh Digunakan',
      selectTopUpAmount: 'Pilih Jumlah Tambah Nilai',
      minTopUp: 'Min: RM 1.00',
      amountPlaceholder: 'cth. 7500.00',
      walletBalancePoolsPolicy: 'Kumpulan Baki Dompet & Dasar',
      orderSummary: 'Ringkasan Pesanan',
      selectedAmount: 'Jumlah Dipilih',
      purchasedFundsPromo: 'Dana dibeli + Bonus promosi',
      youPay: 'Anda Bayar',
      walletValueAfterTopUp: 'Nilai Dompet Selepas Tambah Nilai',
      connectingPaymentGateway: 'Menyambung ke Pintu Masuk Pembayaran...',
      continueToPayment: 'Teruskan ke Pembayaran',
      encryptedPaymentNotice: 'Pintu Masuk Pembayaran Disulitkan 256-bit • Disahkan Webhook',
    },
  },
  showcase: {
    en: {
      notCreated: 'Not Created',
      manageShowcase: 'Manage Event Showcase',
      previewShowcase: 'Preview Showcase',
      viewFullQuality: 'View Full Quality',
      loadingMedia: 'Loading showcase media...',
      moderatorNote: 'Moderator Note:',
      showcaseBlocked: 'Showcase Blocked by Moderation',
      videoPosterThumbnail: 'Video Poster / Thumbnail:',
      autoDefault: 'Auto default',
    },
    zh: {
      notCreated: '未创建',
      manageShowcase: '管理活动展示',
      previewShowcase: '预览展示',
      viewFullQuality: '查看高清原图',
      loadingMedia: '正在加载展示媒体...',
      moderatorNote: '审核员备注：',
      showcaseBlocked: '展示内容已被审核拦截',
      videoPosterThumbnail: '视频封面图 / 缩略图：',
      autoDefault: '自动默认封面',
    },
    ms: {
      notCreated: 'Belum Dicipta',
      manageShowcase: 'Urus Pameran Acara',
      previewShowcase: 'Pratonton Pameran',
      viewFullQuality: 'Lihat Kualiti Penuh',
      loadingMedia: 'Sedang memuatkan media pameran...',
      moderatorNote: 'Nota Moderator:',
      showcaseBlocked: 'Pameran Disekat oleh Moderasi',
      videoPosterThumbnail: 'Poster / Gambar Kecil Video:',
      autoDefault: 'Lalai automatik',
    },
  },
  game: {
    en: {
      gameplayMetrics: 'Gameplay Metrics:',
      testScores: 'Test Scores',
      searchPlayerNickname: 'Search player nickname...',
      resetBoard: 'Reset Board',
      loadingHighScores: 'Loading Event High Scores...',
      deleteScoreEntry: 'Delete Score Entry',
      resetBoardConfirm: 'Reset entire leaderboard?',
      clearTestScoresConfirm: 'Clear all test scores?',
      gameEngines: 'Game Engines',
    },
    zh: {
      gameplayMetrics: '游戏数据指标：',
      testScores: '测试成绩',
      searchPlayerNickname: '搜索玩家昵称...',
      resetBoard: '重置榜单',
      loadingHighScores: '正在加载活动高分榜...',
      deleteScoreEntry: '删除成绩条目',
      resetBoardConfirm: '确定要重置整个排行榜吗？',
      clearTestScoresConfirm: '确定要清除所有测试成绩吗？',
      gameEngines: '游戏引擎库',
    },
    ms: {
      gameplayMetrics: 'Metrik Permainan:',
      testScores: 'Skor Ujian',
      searchPlayerNickname: 'Cari nama samaran pemain...',
      resetBoard: 'Tetapkan Semula Papan',
      loadingHighScores: 'Sedang memuatkan skor tertinggi acara...',
      deleteScoreEntry: 'Padam Entri Skor',
      resetBoardConfirm: 'Tetapkan semula seluruh papan pendahulu?',
      clearTestScoresConfirm: 'Kosongkan semua skor ujian?',
      gameEngines: 'Enjin Permainan',
    },
  },
  studio: {
    en: {
      noThemesYet: 'No custom themes yet',
      browseSystemThemes: 'Browse System Themes',
      noMatchingThemes: 'No matching custom themes',
      cloneAllDefaultThemes: 'Clone All Default Themes',
      unableToLoadThemes: 'Unable to load system themes.',
      loadingSystemThemes: 'Loading system themes...',
      noActiveSystemThemes: 'No active system themes available for this game engine.',
      selectedGame: 'Selected Game:',
      themesToClone: 'Themes to Clone:',
      cloningAll: 'Cloning All...',
      cloneAll: 'Clone All',
      savedToPlatform: 'Saved to Platform',
      saveSystemTheme: 'Save System Theme',
      testPlayLive: 'Test Play Live',
      primary: 'Primary',
      themeNotFound: 'Theme Not Found',
      backToGameThemes: 'Back to Game Themes',
      backToGameDetails: 'Back to Game Details',
    },
    zh: {
      noThemesYet: '暂无自定义主题',
      browseSystemThemes: '浏览系统官方模板',
      noMatchingThemes: '未找到匹配的自定义主题',
      cloneAllDefaultThemes: '克隆所有官方模板',
      unableToLoadThemes: '无法加载系统主题。',
      loadingSystemThemes: '正在加载系统主题...',
      noActiveSystemThemes: '此游戏引擎暂无可用的官方主题模板。',
      selectedGame: '已选游戏：',
      themesToClone: '待克隆主题：',
      cloningAll: '正在克隆全部...',
      cloneAll: '克隆全部',
      savedToPlatform: '已保存至平台',
      saveSystemTheme: '保存系统主题',
      testPlayLive: '试玩测试',
      primary: '默认主主题',
      themeNotFound: '未找到该主题',
      backToGameThemes: '返回游戏主题列表',
      backToGameDetails: '返回游戏详情',
    },
    ms: {
      noThemesYet: 'Tiada tema tersuai lagi',
      browseSystemThemes: 'Lihat Tema Sistem',
      noMatchingThemes: 'Tiada tema tersuai yang sepadan',
      cloneAllDefaultThemes: 'Klon Semua Tema Lalai',
      unableToLoadThemes: 'Tidak dapat memuatkan tema sistem.',
      loadingSystemThemes: 'Sedang memuatkan tema sistem...',
      noActiveSystemThemes: 'Tiada tema sistem aktif tersedia untuk enjin permainan ini.',
      selectedGame: 'Permainan Dipilih:',
      themesToClone: 'Tema untuk Diklon:',
      cloningAll: 'Sedang Mengklon Semua...',
      cloneAll: 'Klon Semua',
      savedToPlatform: 'Disimpan ke Platform',
      saveSystemTheme: 'Simpan Tema Sistem',
      testPlayLive: 'Uji Main Langsung',
      primary: 'Utama',
      themeNotFound: 'Tema Tidak Ditemui',
      backToGameThemes: 'Kembali ke Tema Permainan',
      backToGameDetails: 'Kembali ke Butiran Permainan',
    },
  },
  developer: {
    en: {
      newSystemTheme: 'New System Default Theme',
      setPrimaryDefaultTheme: 'Set as primary default theme',
      allEnginesRegistered: 'All Game Engines Registered',
      slugInUse: 'Slug is already in use by another game',
      engineType: 'Game Engine / Type',
      typeAlreadyRegistered: 'This game type is already registered',
      gameDescPlaceholder: 'Brief description of the game mechanic and player experience...',
      iconPlaceholder: 'Gamepad2',
      draftDeveloperOnly: 'Draft (Developer Only)',
      archived: 'Archived',
      saving: 'Saving...',
      unblockShowcase: 'Unblock Showcase',
      blockShowcase: 'Block Showcase',
      softDeleteShowcase: 'Soft Delete Showcase',
      auditInformation: 'Audit Information:',
      loadingGallery: 'Loading gallery items...',
      openOriginal: 'Open original',
      approveReward300: 'Approve Reward (RM300)',
      showcaseSoftDeleted: 'Showcase Administratively Soft-Deleted',
      rejectFirstEventReward: 'Reject First-Event Showcase Reward',
    },
    zh: {
      newSystemTheme: '新建系统默认主题',
      setPrimaryDefaultTheme: '设为默认主主题',
      allEnginesRegistered: '所有游戏引擎均已注册',
      slugInUse: '该标识别名已被其他游戏占用',
      engineType: '游戏引擎类型',
      typeAlreadyRegistered: '该游戏类型已存在注册项',
      gameDescPlaceholder: '简要描述该游戏玩法机制与玩家体验...',
      iconPlaceholder: 'Gamepad2',
      draftDeveloperOnly: '草稿（仅开发者可见）',
      archived: '已归档',
      saving: '正在保存...',
      unblockShowcase: '解除展示拦截',
      blockShowcase: '拦截该展示',
      softDeleteShowcase: '管理员软删除展示',
      auditInformation: '审计详细信息：',
      loadingGallery: '正在加载图库素材...',
      openOriginal: '查看原始大图',
      approveReward300: '批准奖励 (RM300)',
      showcaseSoftDeleted: '该展示已被管理员软删除',
      rejectFirstEventReward: '拒绝首单活动展示奖励',
    },
    ms: {
      newSystemTheme: 'Tema Lalai Sistem Baharu',
      setPrimaryDefaultTheme: 'Tetapkan sebagai tema lalai utama',
      allEnginesRegistered: 'Semua Enjin Permainan Didaftarkan',
      slugInUse: 'Slug sudah digunakan oleh permainan lain',
      engineType: 'Enjin / Jenis Permainan',
      typeAlreadyRegistered: 'Jenis permainan ini sudah didaftarkan',
      gameDescPlaceholder: 'Penerangan ringkas tentang mekanik permainan dan pengalaman pemain...',
      iconPlaceholder: 'Gamepad2',
      draftDeveloperOnly: 'Draf (Pembangun Sahaja)',
      archived: 'Diarkibkan',
      saving: 'Sedang menyimpan...',
      unblockShowcase: 'Nyahsekat Pameran',
      blockShowcase: 'Sekat Pameran',
      softDeleteShowcase: 'Padam Lembut Pameran Secara Pentadbiran',
      auditInformation: 'Maklumat Audit:',
      loadingGallery: 'Sedang memuatkan item galeri...',
      openOriginal: 'Buka asal',
      approveReward300: 'Luluskan Ganjaran (RM300)',
      showcaseSoftDeleted: 'Pameran Dipadamkan Secara Pentadbiran',
      rejectFirstEventReward: 'Tolak Ganjaran Pameran Acara Pertama',
    },
  },
  team: {
    en: {
      removeMember: 'Remove member',
    },
    zh: {
      removeMember: '移除成员',
    },
    ms: {
      removeMember: 'Alih keluar ahli',
    },
  },
};

function injectKeys(filePath: string, lang: 'en' | 'zh' | 'ms') {
  let content = fs.readFileSync(filePath, 'utf8');

  for (const [namespace, langData] of Object.entries(newTranslations)) {
    const keys = langData[lang];
    // Find namespace opening: e.g. "  namespace: {"
    const regex = new RegExp(`(\\n\\s*${namespace}:\\s*\\{[\\s\\S]*?)(\\n\\s*\\},)`, 'm');
    const match = content.match(regex);
    if (!match) {
      console.error(`Namespace ${namespace} not found in ${filePath}`);
      continue;
    }

    let injection = '';
    for (const [k, v] of Object.entries(keys)) {
      // Check if key already present in namespace block
      if (match[1].includes(`${k}:`)) {
        continue;
      }
      const escaped = (v as string).replace(/'/g, "\\'");
      injection += `    ${k}: '${escaped}',\n`;
    }

    if (injection) {
      content = content.replace(regex, `$1\n${injection}  },`);
    }
  }

  fs.writeFileSync(filePath, content, 'utf8');
  console.log(`Updated ${filePath}`);
}

injectKeys(enPath, 'en');
injectKeys(zhPath, 'zh');
injectKeys(msPath, 'ms');
console.log('Finished updating all three locale files.');
