import fs from 'fs';
import path from 'path';

const enPath = path.resolve('src/locales/en.ts');
const zhPath = path.resolve('src/locales/zh-CN.ts');
const msPath = path.resolve('src/locales/ms-MY.ts');

export const newTranslations: Record<string, { en: Record<string, string>; zh: Record<string, string>; ms: Record<string, string> }> = {
  common: {
    en: {
      manageGame: 'Manage Game',
      demo: 'Demo',
      searchGamesPlaceholder: 'Search games by title, type, or tags...',
      platformGameCatalog: 'Platform Game Catalog',
      interactiveEventGames: 'Interactive Event Games',
      interactiveEventGamesDesc: 'Explore available game engines, manage branded themes, customize physics and visuals, and configure games for your live promotional events.',
      allGameTypes: 'All Game Types',
      allStatuses: 'All Statuses',
      activeOnly: 'Active Only',
      noGamesFound: 'No games found',
      noGamesMatchFilter: 'No games match your active filters. Try adjusting your search query.',
      noGamesInCatalog: 'No games are available in this catalog yet.',
      themesConfigured: 'Configured',
      eventsLinked: 'Linked',
      themeCount: '{{count}} Themes',
      singleThemeCount: '1 Theme',
      eventCount: '{{count}} Events',
      singleEventCount: '1 Event',
      stepNumber: 'Step {{step}}',
    },
    zh: {
      manageGame: '管理游戏',
      demo: '演示试玩',
      searchGamesPlaceholder: '按游戏名称、类型或标签搜索...',
      platformGameCatalog: '平台游戏目录',
      interactiveEventGames: '互动活动游戏',
      interactiveEventGamesDesc: '探索可用游戏引擎、管理品牌主题、定制物理参数与视觉效果，并为线下推广活动配置互动游戏。',
      allGameTypes: '所有游戏类型',
      allStatuses: '全部状态',
      activeOnly: '仅有效',
      noGamesFound: '未找到游戏',
      noGamesMatchFilter: '没有符合当前筛选条件的游戏，请尝试调整搜索词。',
      noGamesInCatalog: '目录中暂无可用游戏。',
      themesConfigured: '已配置',
      eventsLinked: '已关联',
      themeCount: '{{count}} 个主题',
      singleThemeCount: '1 个主题',
      eventCount: '{{count}} 个活动',
      singleEventCount: '1 个活动',
      stepNumber: '第 {{step}} 步',
    },
    ms: {
      manageGame: 'Urus Permainan',
      demo: 'Demo',
      searchGamesPlaceholder: 'Cari permainan mengikut tajuk, jenis atau tag...',
      platformGameCatalog: 'Katalog Permainan Platform',
      interactiveEventGames: 'Permainan Acara Interaktif',
      interactiveEventGamesDesc: 'Terokai enjin permainan yang tersedia, urus tema berjenama, sesuaikan fizik dan visual, serta konfigurasikan permainan untuk acara promosi langsung anda.',
      allGameTypes: 'Semua Jenis Permainan',
      allStatuses: 'Semua Status',
      activeOnly: 'Aktif Sahaja',
      noGamesFound: 'Tiada permainan dijumpai',
      noGamesMatchFilter: 'Tiada permainan sepadan dengan penapis aktif anda. Cuba laraskan pertanyaan carian anda.',
      noGamesInCatalog: 'Belum ada permainan tersedia dalam katalog ini.',
      themesConfigured: 'Dikonfigurasikan',
      eventsLinked: 'Dipautkan',
      themeCount: '{{count}} Tema',
      singleThemeCount: '1 Tema',
      eventCount: '{{count}} Acara',
      singleEventCount: '1 Acara',
      stepNumber: 'Langkah {{step}}',
    },
  },
  onboarding: {
    en: {
      workspaceSetup: 'Workspace Setup',
      stepTheme: 'Set Up Theme',
      stepEvent: 'Create Event',
      stepLaunch: 'Launch Event',
      step2: 'Step 2',
      step3: 'Step 3',
      heroTitle: "Let's set up your event theme",
      heroSubtitle: 'Before creating your first event, customize your theme to match your brand. Every interactive game requires branded visuals, custom colors, and score targets to go live.',
      themeReady: 'Your organization has a customized theme!',
      themeReadyDesc: 'You can continue directly to event creation or customize your theme further.',
      themeRequired: 'Theme setup is required',
      themeRequiredDesc: 'Event creation is locked until you save your brand theme. Once saved, event creation will automatically unlock.',
      brandColors: 'Brand Colors',
      brandColorsDesc: 'Logos & palette',
      gameTargets: 'Game Targets',
      gameTargetsDesc: 'Rewards & hazards',
      audioSfx: 'Audio & SFX',
      audioSfxDesc: 'Catch & win cues',
      customizeMyTheme: 'Customize My Theme',
      preparingThemeEditor: 'Preparing Theme Editor...',
      createFirstEvent: 'Create First Event',
      returnNotice: 'You can return to the dashboard at any time, but event creation will remain locked until a theme is saved.',
    },
    zh: {
      workspaceSetup: '工作区设置',
      stepTheme: '设置品牌主题',
      stepEvent: '创建活动',
      stepLaunch: '上线活动',
      step2: '第 2 步',
      step3: '第 3 步',
      heroTitle: '设置您的活动品牌主题',
      heroSubtitle: '在创建首个活动前，请定制符合您品牌视觉的主题。每个互动游戏均需配置品牌视觉、自定义配色与得分目标方可正式上线。',
      themeReady: '您的机构已拥有定制主题！',
      themeReadyDesc: '您可以直接继续创建活动，或进一步微调您的主题。',
      themeRequired: '必须先设置品牌主题',
      themeRequiredDesc: '在保存品牌主题之前，活动创建功能保持锁定。主题保存后将自动解锁。',
      brandColors: '品牌配色',
      brandColorsDesc: '企业标识与主题色',
      gameTargets: '游戏目标物',
      gameTargetsDesc: '加分项与避开障碍',
      audioSfx: '音效与背景音乐',
      audioSfxDesc: '得分与通关提示音',
      customizeMyTheme: '定制我的品牌主题',
      preparingThemeEditor: '正在准备主题编辑器...',
      createFirstEvent: '创建首个活动',
      returnNotice: '您可以随时返回控制台，但在保存主题之前，活动创建将保持锁定。',
    },
    ms: {
      workspaceSetup: 'Persediaan Ruang Kerja',
      stepTheme: 'Sediakan Tema',
      stepEvent: 'Cipta Acara',
      stepLaunch: 'Lancarkan Acara',
      step2: 'Langkah 2',
      step3: 'Langkah 3',
      heroTitle: 'Mari sediakan tema acara anda',
      heroSubtitle: 'Sebelum mencipta acara pertama anda, suaikan tema anda agar sepadan dengan jenama anda. Setiap permainan interaktif memerlukan visual berjenama, warna tersuai dan sasaran skor untuk disiarkan secara langsung.',
      themeReady: 'Organisasi anda mempunyai tema tersuai!',
      themeReadyDesc: 'Anda boleh terus ke penciptaan acara atau menyesuaikan tema anda dengan lebih lanjut.',
      themeRequired: 'Persediaan tema diperlukan',
      themeRequiredDesc: 'Penciptaan acara dikunci sehingga anda menyimpan tema jenama anda. Setelah disimpan, penciptaan acara akan dibuka kunci secara automatik.',
      brandColors: 'Warna Jenama',
      brandColorsDesc: 'Logo & palet warna',
      gameTargets: 'Sasaran Permainan',
      gameTargetsDesc: 'Ganjaran & halangan',
      audioSfx: 'Audio & SFX',
      audioSfxDesc: 'Kesan tangkapan & kemenangan',
      customizeMyTheme: 'Sesuaikan Tema Saya',
      preparingThemeEditor: 'Menyediakan Penyunting Tema...',
      createFirstEvent: 'Cipta Acara Pertama',
      returnNotice: 'Anda boleh kembali ke papan pemuka pada bila-bila masa, tetapi penciptaan acara akan kekal dikunci sehingga tema disimpan.',
    },
  },
  studio: {
    en: {
      gameTitleAndCopy: 'Game Title & Copy',
      taglineSubtitle: 'Tagline / Subtitle',
      themeDescriptionNotes: 'Theme Description (Internal Notes)',
      eventClientLogo: 'Event / Client Logo',
      displayClientLogoInGame: 'Display Client Logo in Game',
      colorPaletteAndHud: 'Color Palette & HUD',
      hudScoreColor: 'HUD Score Color',
      ambientWeatherAndParticles: 'Ambient Weather & Particles',
      gameBackgroundCanvas: 'Game Background Canvas',
      activeBackground: 'Active Background',
      uploadingNewBackground: 'Uploading new background...',
      cardBackArtworkAndDeckStyling: 'Card Back Artwork & Deck Styling',
      cardBackFaceArtwork: 'Card Back Face Artwork',
      uploadingNewCardBack: 'Uploading new card back...',
      cardFrontBackground: 'Card Front Background',
      faceUp: 'Face-Up',
      backgroundOpacity: 'Background Opacity',
      matchSuccessBackground: 'Match Success Background',
      matched: 'Matched',
      cardFrontBorderColor: 'Card Front Border Color',
      matchedPairBorderColor: 'Matched Pair Border Color',
      catcherBasket: 'Catcher / Basket',
      catcherName: 'Catcher Name',
      catcherArtwork: 'Catcher Artwork',
      uploadingNewCatcher: 'Uploading new catcher...',
      uploadImage: 'Upload Image',
      catcherWidth: 'Catcher Width',
      catchOpeningRatio: 'Catch Opening Ratio',
      advancedCollisionPhysicsTuning: 'Advanced Collision & Physics Tuning',
      matchDynamicsAndSpeed: 'Match Dynamics & Speed',
      progressiveDifficultyEscalation: 'Progressive Difficulty Escalation',
      spawnDelay: 'Spawn Delay:',
      itemSpeedRange: 'Item Speed Range:',
      advancedPhysicsAndStageIntervalOverrides: 'Advanced Physics & Stage Interval Overrides',
      baseFallVelocity: 'Base Fall Velocity (px/s)',
      minSpawnInterval: 'Min Spawn Interval (ms)',
      maxSpawnInterval: 'Max Spawn Interval (ms)',
      spriteArtwork: 'Sprite Artwork',
      uploadingSprite: 'Uploading sprite...',
      artwork: 'Artwork:',
      gameSize: 'Game Size:',
      reactionGantrySequence: 'Reaction Gantry Sequence',
      reset8Pairs: 'Reset 8 Pairs',
      addPair: 'Add Pair',
      addItem: 'Add Item',
      gridBoardRequirement: '4x4 Grid Board Requirement:',
      relativeSpawnChanceDistribution: 'Relative Spawn Chance Distribution',
      positiveItem: 'Positive Item (+Pts)',
      hazardBomb: 'Hazard / Bomb (-Pts)',
      bonusSpecial: 'Bonus Special (+50 Pts)',
      speed: 'Speed',
      weight: 'Weight',
      scale: 'Scale',
      resetAllLayout: 'Reset All Layout',
      landscapeLayout: 'Landscape Layout',
      landscapeLayoutDesc: '1024 × 576 base layout',
      portraitLayout: 'Portrait Layout',
      portraitLayoutDesc: '576 × 1024 vertical layout',
      elementVisibility: 'Element Visibility',
      horizontalX: 'Horizontal X (%)',
      verticalY: 'Vertical Y (%)',
      widthSize: 'Width Size (%)',
      quickAlignmentGrid: 'Quick 9-Point Alignment Grid',
      oneClickSnap: '1-click snap to preset position',
      liveDragResizeViewport: 'Live Drag & Resize in Simulation Viewport:',
      simulationPaused: 'Simulation Paused',
      activeTheme: 'Active Theme',
      restartSimulation: 'Restart Simulation',
      applyAndResume: 'Apply & Resume',
      instantDropTester: 'Instant Drop Tester:',
      drop: 'Drop:',
      clientLogo: 'Client Logo',
      movesHud: 'Moves Display',
      pairsHud: 'Pairs Display',
    },
    zh: {
      gameTitleAndCopy: '游戏标题与文案',
      taglineSubtitle: '副标题 / 口号',
      themeDescriptionNotes: '主题说明（内部备注）',
      eventClientLogo: '活动 / 品牌企业标识',
      displayClientLogoInGame: '在游戏界面展示品牌 Logo',
      colorPaletteAndHud: '配色方案与 HUD 色彩',
      hudScoreColor: 'HUD 计分色彩',
      ambientWeatherAndParticles: '环境天气与粒子特效',
      gameBackgroundCanvas: '游戏主背景画布',
      activeBackground: '当前生效背景',
      uploadingNewBackground: '正在上传新背景...',
      cardBackArtworkAndDeckStyling: '卡牌背面图案与卡组样式',
      cardBackFaceArtwork: '卡背主图',
      uploadingNewCardBack: '正在上传新卡背...',
      cardFrontBackground: '卡牌正面底色',
      faceUp: '正面朝上',
      backgroundOpacity: '背景不透明度',
      matchSuccessBackground: '配对成功背景色',
      matched: '已配对',
      cardFrontBorderColor: '卡牌正面边框颜色',
      matchedPairBorderColor: '配对成功边框颜色',
      catcherBasket: '接取器 / 托盘',
      catcherName: '接取器名称',
      catcherArtwork: '接取器图案',
      uploadingNewCatcher: '正在上传新接取器...',
      uploadImage: '上传图片',
      catcherWidth: '接取器宽度',
      catchOpeningRatio: '开口接取范围比例',
      advancedCollisionPhysicsTuning: '高级碰撞检测与物理调节',
      matchDynamicsAndSpeed: '比赛节奏与速度',
      progressiveDifficultyEscalation: '难度逐步递进机制',
      spawnDelay: '掉落延迟：',
      itemSpeedRange: '物品下落速度区间：',
      advancedPhysicsAndStageIntervalOverrides: '高级物理引擎与阶段间隔覆盖',
      baseFallVelocity: '基础下落速度 (px/s)',
      minSpawnInterval: '最小生成间隔 (ms)',
      maxSpawnInterval: '最大生成间隔 (ms)',
      spriteArtwork: '物品精灵图案',
      uploadingSprite: '正在上传精灵图...',
      artwork: '图案：',
      gameSize: '游戏渲染尺寸：',
      reactionGantrySequence: '反应灯龙门架序列',
      reset8Pairs: '重置 8 组卡牌',
      addPair: '添加卡牌对',
      addItem: '添加物品',
      gridBoardRequirement: '4x4 棋盘网格规格要求：',
      relativeSpawnChanceDistribution: '相对生成概率权重分布',
      positiveItem: '加分物品 (+分)',
      hazardBomb: '危险炸弹 (-分)',
      bonusSpecial: '特殊奖励物品 (+50分)',
      speed: '速度',
      weight: '权重',
      scale: '缩放',
      resetAllLayout: '重置所有布局',
      landscapeLayout: '横屏布局',
      landscapeLayoutDesc: '1024 × 576 基础布局',
      portraitLayout: '竖屏布局',
      portraitLayoutDesc: '576 × 1024 竖屏布局',
      elementVisibility: '元素可见性',
      horizontalX: '水平位置 X (%)',
      verticalY: '垂直位置 Y (%)',
      widthSize: '宽度尺寸 (%)',
      quickAlignmentGrid: '9 点快捷吸附对齐网格',
      oneClickSnap: '一键吸附至预设位置',
      liveDragResizeViewport: '仿真画布实时拖拽与缩放：',
      simulationPaused: '模拟已暂停',
      activeTheme: '当前主题',
      restartSimulation: '重新开始模拟',
      applyAndResume: '应用并继续',
      instantDropTester: '即时下落测试工具：',
      drop: '掉落：',
      clientLogo: '品牌 Logo',
      movesHud: '移动步数显示',
      pairsHud: '配对显示',
    },
    ms: {
      gameTitleAndCopy: 'Tajuk & Teks Permainan',
      taglineSubtitle: 'Baris Tegar / Sari Kata',
      themeDescriptionNotes: 'Penerangan Tema (Nota Dalaman)',
      eventClientLogo: 'Logo Acara / Jenama Klien',
      displayClientLogoInGame: 'Papar Logo Klien dalam Permainan',
      colorPaletteAndHud: 'Palet Warna & Paparan HUD',
      hudScoreColor: 'Warna Skor HUD',
      ambientWeatherAndParticles: 'Cuaca Persekitaran & Zarah',
      gameBackgroundCanvas: 'Kanvas Latar Belakang Permainan',
      activeBackground: 'Latar Belakang Aktif',
      uploadingNewBackground: 'Memuat naik latar belakang baharu...',
      cardBackArtworkAndDeckStyling: 'Karya Belakang Kad & Gaya Dek',
      cardBackFaceArtwork: 'Karya Muka Belakang Kad',
      uploadingNewCardBack: 'Memuat naik belakang kad baharu...',
      cardFrontBackground: 'Latar Belakang Depan Kad',
      faceUp: 'Menghadap Ke Atas',
      backgroundOpacity: 'Kelegapan Latar Belakang',
      matchSuccessBackground: 'Latar Belakang Padanan Berjaya',
      matched: 'Dipadankan',
      cardFrontBorderColor: 'Warna Sempadan Depan Kad',
      matchedPairBorderColor: 'Warna Sempadan Pasangan Padan',
      catcherBasket: 'Penangkap / Bakul',
      catcherName: 'Nama Penangkap',
      catcherArtwork: 'Karya Penangkap',
      uploadingNewCatcher: 'Memuat naik penangkap baharu...',
      uploadImage: 'Muat Naik Imej',
      catcherWidth: 'Lebar Penangkap',
      catchOpeningRatio: 'Nisbah Bukaan Tangkapan',
      advancedCollisionPhysicsTuning: 'Penalaan Fizik & Perlanggaran Lanjutan',
      matchDynamicsAndSpeed: 'Dinamik & Kelajuan Perlawanan',
      progressiveDifficultyEscalation: 'Peningkatan Kesukaran Progresif',
      spawnDelay: 'Kelewatan Muncul:',
      itemSpeedRange: 'Julat Kelajuan Item:',
      advancedPhysicsAndStageIntervalOverrides: 'Fizik Lanjutan & Penggantian Selang Peringkat',
      baseFallVelocity: 'Halaju Jatuh Asas (px/s)',
      minSpawnInterval: 'Selang Kemunculan Min (ms)',
      maxSpawnInterval: 'Selang Kemunculan Maks (ms)',
      spriteArtwork: 'Karya Seni Sprite',
      uploadingSprite: 'Memuat naik sprite...',
      artwork: 'Karya Seni:',
      gameSize: 'Saiz Permainan:',
      reactionGantrySequence: 'Jujukan Gantri Reaksi',
      reset8Pairs: 'Tetapkan Semula 8 Pasang',
      addPair: 'Tambah Pasangan',
      addItem: 'Tambah Item',
      gridBoardRequirement: 'Keperluan Papan Grid 4x4:',
      relativeSpawnChanceDistribution: 'Taburan Peluang Muncul Relatif',
      positiveItem: 'Item Positif (+Mata)',
      hazardBomb: 'Bahaya / Bom (-Mata)',
      bonusSpecial: 'Bonus Khas (+50 Mata)',
      speed: 'Kelajuan',
      weight: 'Berat',
      scale: 'Skala',
      resetAllLayout: 'Tetapkan Semula Semua Susun Atur',
      landscapeLayout: 'Susun Atur Landskap',
      landscapeLayoutDesc: 'Susun atur asas 1024 × 576',
      portraitLayout: 'Susun Atur Potret',
      portraitLayoutDesc: 'Susun atur menegak 576 × 1024',
      elementVisibility: 'Keterlihatan Elemen',
      horizontalX: 'X Mendatar (%)',
      verticalY: 'Y Menegak (%)',
      widthSize: 'Saiz Lebar (%)',
      quickAlignmentGrid: 'Grid Penjajaran 9-Titik Pantas',
      oneClickSnap: '1-klik tangkap ke kedudukan pratetap',
      liveDragResizeViewport: 'Seret & Saiz Semula Langsung dalam Port Paparan Simulasi:',
      simulationPaused: 'Simulasi Dijeda',
      activeTheme: 'Tema Aktif',
      restartSimulation: 'Mulakan Semula Simulasi',
      applyAndResume: 'Gunakan & Sambung Semula',
      instantDropTester: 'Penguji Gugur Serta-merta:',
      drop: 'Gugurkan:',
      clientLogo: 'Logo Klien',
      movesHud: 'Paparan Pergerakan',
      pairsHud: 'Paparan Pasangan',
    },
  },
};

function injectNamespaceOrKeys(filePath: string, lang: 'en' | 'zh' | 'ms') {
  let content = fs.readFileSync(filePath, 'utf8');

  for (const [namespace, langData] of Object.entries(newTranslations)) {
    const keys = langData[lang];
    const regex = new RegExp(`(\\n\\s*${namespace}:\\s*\\{[\\s\\S]*?)(\\n\\s*\\},)`, 'm');
    const match = content.match(regex);

    if (!match) {
      // Namespace does not exist, inject it right before the last closing bracket "};"
      let newBlock = `  ${namespace}: {\n`;
      for (const [k, v] of Object.entries(keys)) {
        const escaped = (v as string).replace(/'/g, "\\'");
        newBlock += `    ${k}: '${escaped}',\n`;
      }
      newBlock += `  },\n`;

      const lastBraceIndex = content.lastIndexOf('};');
      if (lastBraceIndex !== -1) {
        content = content.slice(0, lastBraceIndex) + newBlock + content.slice(lastBraceIndex);
        console.log(`Created namespace ${namespace} in ${filePath}`);
      }
    } else {
      // Namespace exists, inject missing keys
      let injection = '';
      for (const [k, v] of Object.entries(keys)) {
        if (match[1].includes(`${k}:`)) {
          continue;
        }
        const escaped = (v as string).replace(/'/g, "\\'");
        injection += `    ${k}: '${escaped}',\n`;
      }

      if (injection) {
        content = content.replace(regex, `$1\n${injection}  },`);
        console.log(`Injected keys into ${namespace} in ${filePath}`);
      }
    }
  }

  fs.writeFileSync(filePath, content, 'utf8');
}

injectNamespaceOrKeys(enPath, 'en');
injectNamespaceOrKeys(zhPath, 'zh');
injectNamespaceOrKeys(msPath, 'ms');
console.log('Batch 5-8 keys injection completed successfully.');
