import fs from 'fs';
import path from 'path';

const enPath = path.resolve('src/locales/en.ts');
const zhPath = path.resolve('src/locales/zh-CN.ts');
const msPath = path.resolve('src/locales/ms-MY.ts');

export const translations: Record<string, { en: Record<string, string>; zh: Record<string, string>; ms: Record<string, string> }> = {
  customizers: {
    en: {
      catcherArtworkDimensions: 'Catcher Artwork & Dimensions',
      replaceGraphic: 'Replace Graphic',
      catcherScalePhysics: 'Catcher Scale, Catch Area & Physics',
      catcherName: 'Catcher Name',
      catcherNamePlaceholder: 'e.g. Woven Basket',
      catchSweetSpot: 'Catch Sweet Spot',
      fallingObjectsCollectibles: 'Falling Objects & Collectibles',
      addItem: 'Add Item',
      itemName: 'Item Name',
      pointsValue: 'Points Value',
      spawnFrequency: 'Spawn Frequency',
      speedModifier: 'Speed Modifier',
      proportionalScale: 'Proportional Scale',
      matchDynamicsSpeed: 'Match Dynamics & Speed',
      sessionLengthDesc: 'Session length before time expires',
      speedRateDesc: 'Speed rate of falling objects',
      spawnIntervalDesc: 'Delay between consecutive item spawns',
      cardBackPatternArtwork: 'Card Back Pattern & Artwork',
      activeCardBackCover: 'Active Card Back Cover',
      replaceArtwork: 'Replace Artwork',
      cardFrontBackground: 'Card Front Background',
      faceUp: 'Face-Up',
      backgroundColor: 'Background Color',
      backgroundOpacity: 'Background Opacity',
      transparent: '0% (Transparent)',
      solid: '100% (Solid)',
      matchSuccessBackground: 'Match Success Background',
      matchSuccessBorder: 'Match Success Border',
      mismatchAlertBorder: 'Mismatch Alert Border',
      cardLibrary: 'Card Library',
      boardLayoutArrangement: 'Board Layout & Card Arrangement',
      layoutGrid: 'Grid',
      layoutScattered: 'Random / Scattered',
      layoutUpDown: 'Up-Down',
      layoutUpDownRotated: 'Up-Down + Random Rotation',
      cardDimensionsShape: 'Card Dimensions, Shape & Rotation',
      rotationUpright: 'Upright (0°)',
      rotationNone: 'No rotation',
      rotationFixed: 'Fixed Angle',
      rotationFixedDesc: 'Uniform angle',
      rotationRandom: 'Random Tilt',
      rotationRandomDesc: 'Stable per card',
      sessionTimerMismatch: 'Session Timer & Mismatch Reveal',
      scoringComboMultipliers: 'Scoring & Combo Multipliers',
      baseMatchPoints: 'Base Match Points',
      comboStreakBonus: 'Combo Streak Bonus',
      cardFlip: 'Card Flip',
      matchChime: 'Match Chime',
      mismatchBuzz: 'Mismatch Buzz',
      victoryFanfare: 'Victory Fanfare',
      roundsFast: '1 (Fast)',
      roundsStandard: '5 (Standard)',
      roundsThorough: '10 (Thorough)',
      lights3: '3 Lights',
      lights4: '4 Lights',
      lights5: '5 (F1 Classic)',
      stepRapid: '400ms (Rapid)',
      stepClassic: '1000ms (Classic)',
      stepDeliberate: '1500ms (Deliberate)',
      jumpRetry: 'Retry Round (Discard Jump Start)',
      jumpPenalty: '+1000ms Penalty Added',
      jumpDisqualify: 'Mark Round as Disqualified',
      minDelay: 'Minimum Delay',
      maxDelay: 'Maximum Delay',
      lensCircular: 'Circular Lens (Classic)',
      lensRoundedSquare: 'Rounded Square',
      lensCapsule: 'Vertical Capsule / Pill',
      signalLightsOut: 'Lights Out (Formula 1 Standard)',
      signalAllGreen: 'All Turn Green',
      lightTick: 'Light Tick',
      lightsOutChime: 'Lights Out Chime',
      falseStartBuzz: 'False Start Buzz',
      gameScreensCustomization: 'Game Screens Customization',
      startScreen: 'Start Screen',
      resultScreen: 'Result Screen',
      startScreenVisualCanvasEditor: 'Start Screen Visual Canvas Editor',
      openStartScreenEditor: 'Open Start Screen Editor',
      resultScreenVisualCanvasEditor: 'Result Screen Visual Canvas Editor',
      openResultScreenEditor: 'Open Result Screen Editor',
      viewport: 'Viewport:',
      interactiveCanvasPreview: 'Interactive Scaled Canvas Preview (1024 × 576)',
    },
    zh: {
      catcherArtworkDimensions: '接球容器图案与尺寸',
      replaceGraphic: '替换图案',
      catcherScalePhysics: '接球容器缩放、判定区与物理',
      catcherName: '接球容器名称',
      catcherNamePlaceholder: '例如：编织提篮',
      catchSweetSpot: '最佳接取判定区',
      fallingObjectsCollectibles: '掉落物体与收集品',
      addItem: '添加物品',
      itemName: '物品名称',
      pointsValue: '分数值',
      spawnFrequency: '生成频率',
      speedModifier: '速度修正',
      proportionalScale: '等比缩放',
      matchDynamicsSpeed: '对局动态与速度',
      sessionLengthDesc: '回合结束前的有效时长',
      speedRateDesc: '掉落物品的下落速度',
      spawnIntervalDesc: '连续物品生成的间隔时间',
      cardBackPatternArtwork: '卡背图案与外观',
      activeCardBackCover: '当前卡背封面',
      replaceArtwork: '更换图片',
      cardFrontBackground: '卡牌正面背景',
      faceUp: '正面朝上',
      backgroundColor: '背景颜色',
      backgroundOpacity: '背景透明度',
      transparent: '0% (完全透明)',
      solid: '100% (完全不透明)',
      matchSuccessBackground: '配对成功背景',
      matchSuccessBorder: '配对成功边框',
      mismatchAlertBorder: '配对失败提醒边框',
      cardLibrary: '卡牌库',
      boardLayoutArrangement: '牌盘布局与卡牌排列',
      layoutGrid: '网格排列',
      layoutScattered: '随机分散',
      layoutUpDown: '上下交错',
      layoutUpDownRotated: '上下交错 + 随机微倾斜',
      cardDimensionsShape: '卡牌尺寸、外形与角度',
      rotationUpright: '正立 (0°)',
      rotationNone: '无倾斜',
      rotationFixed: '固定倾角',
      rotationFixedDesc: '所有卡牌统一角度',
      rotationRandom: '随机倾斜',
      rotationRandomDesc: '每张卡牌固定微角度',
      sessionTimerMismatch: '对局倒计时与翻开展示时长',
      scoringComboMultipliers: '得分与连击加成系数',
      baseMatchPoints: '单次配对基础分',
      comboStreakBonus: '连续命中连击奖励',
      cardFlip: '翻牌音效',
      matchChime: '配对成功提示音',
      mismatchBuzz: '配对失败提示音',
      victoryFanfare: '通关胜利音效',
      roundsFast: '1 回合 (极速)',
      roundsStandard: '5 回合 (标准)',
      roundsThorough: '10 回合 (严谨)',
      lights3: '3 盏灯',
      lights4: '4 盏灯',
      lights5: '5 盏灯 (F1经典)',
      stepRapid: '400ms (急促)',
      stepClassic: '1000ms (经典节奏)',
      stepDeliberate: '1500ms (舒缓)',
      jumpRetry: '重新本轮 (抢跑重开)',
      jumpPenalty: '+1000ms 惩罚耗时',
      jumpDisqualify: '直接判罚本轮出局',
      minDelay: '最小熄灯延迟',
      maxDelay: '最大熄灯延迟',
      lensCircular: '圆形透镜 (经典)',
      lensRoundedSquare: '圆角矩形',
      lensCapsule: '垂直胶囊形',
      signalLightsOut: '五灯熄灭 (F1标准信号)',
      signalAllGreen: '全数变绿起步',
      lightTick: '逐盏亮灯嘀嗒音',
      lightsOutChime: '熄灯发车提示音',
      falseStartBuzz: '抢跑违规蜂鸣',
      gameScreensCustomization: '游戏页面自定义',
      startScreen: '开始界面',
      resultScreen: '结算界面',
      startScreenVisualCanvasEditor: '开始界面可视化画布编辑器',
      openStartScreenEditor: '打开开始界面编辑器',
      resultScreenVisualCanvasEditor: '结算界面可视化画布编辑器',
      openResultScreenEditor: '打开结算界面编辑器',
      viewport: '视口：',
      interactiveCanvasPreview: '交互式等比画布预览 (1024 × 576)',
    },
    ms: {
      catcherArtworkDimensions: 'Karya Seni & Dimensi Penangkap',
      replaceGraphic: 'Ganti Grafik',
      catcherScalePhysics: 'Skala, Kawasan & Fizik Penangkap',
      catcherName: 'Nama Penangkap',
      catcherNamePlaceholder: 'cth. Bakul Anyaman',
      catchSweetSpot: 'Zon Tangkapan Tepat',
      fallingObjectsCollectibles: 'Objek Jatuh & Koleksi',
      addItem: 'Tambah Item',
      itemName: 'Nama Item',
      pointsValue: 'Nilai Mata',
      spawnFrequency: 'Kekerapan Kemunculan',
      speedModifier: 'Pengubah Kelajuan',
      proportionalScale: 'Skala Berkadar',
      matchDynamicsSpeed: 'Dinamik & Kelajuan Perlawanan',
      sessionLengthDesc: 'Tempoh pusingan sebelum masa tamat',
      speedRateDesc: 'Kadar kelajuan objek jatuh',
      spawnIntervalDesc: 'Kelewatan antara kemunculan item berturutan',
      cardBackPatternArtwork: 'Corak & Karya Seni Belakang Kad',
      activeCardBackCover: 'Kulit Belakang Kad Aktif',
      replaceArtwork: 'Ganti Karya Seni',
      cardFrontBackground: 'Latar Belakang Hadapan Kad',
      faceUp: 'Menghadap Ke Atas',
      backgroundColor: 'Warna Latar Belakang',
      backgroundOpacity: 'Kelegapan Latar Belakang',
      transparent: '0% (Lutsinar)',
      solid: '100% (Pejal)',
      matchSuccessBackground: 'Latar Belakang Kejayaan Padanan',
      matchSuccessBorder: 'Sempadan Kejayaan Padanan',
      mismatchAlertBorder: 'Sempadan Amaran Ketidakpadanan',
      cardLibrary: 'Perpustakaan Kad',
      boardLayoutArrangement: 'Susun Atur Papan & Susunan Kad',
      layoutGrid: 'Grid',
      layoutScattered: 'Rawak / Berselerak',
      layoutUpDown: 'Atas-Bawah',
      layoutUpDownRotated: 'Atas-Bawah + Putaran Rawak',
      cardDimensionsShape: 'Dimensi, Bentuk & Putaran Kad',
      rotationUpright: 'Tegak (0°)',
      rotationNone: 'Tiada putaran',
      rotationFixed: 'Sudut Tetap',
      rotationFixedDesc: 'Sudut seragam',
      rotationRandom: 'Condong Rawak',
      rotationRandomDesc: 'Stabil bagi setiap kad',
      sessionTimerMismatch: 'Pemasa Sesi & Pendedahan Ketidakpadanan',
      scoringComboMultipliers: 'Pemberian Mata & Pengganda Kombo',
      baseMatchPoints: 'Mata Padanan Asas',
      comboStreakBonus: 'Bonus Rentetan Kombo',
      cardFlip: 'Balikan Kad',
      matchChime: 'Lonceng Padanan',
      mismatchBuzz: 'Dengung Ketidakpadanan',
      victoryFanfare: 'Tiupan Kemenangan',
      roundsFast: '1 (Pantas)',
      roundsStandard: '5 (Standard)',
      roundsThorough: '10 (Teliti)',
      lights3: '3 Lampu',
      lights4: '4 Lampu',
      lights5: '5 (Klasik F1)',
      stepRapid: '400ms (Cepat)',
      stepClassic: '1000ms (Klasik)',
      stepDeliberate: '1500ms (Santai)',
      jumpRetry: 'Ulang Pusingan (Batal Mula Awal)',
      jumpPenalty: '+1000ms Penalti Ditambah',
      jumpDisqualify: 'Tandakan Pusingan Dibatalkan Kelayakan',
      minDelay: 'Kelewatan Minimum',
      maxDelay: 'Kelewatan Maksimum',
      lensCircular: 'Kanta Bulat (Klasik)',
      lensRoundedSquare: 'Segi Empat Berbucu Bulat',
      lensCapsule: 'Kapsul / Pil Menegak',
      signalLightsOut: 'Lampu Padam (Standard Formula 1)',
      signalAllGreen: 'Semua Jadi Hijau',
      lightTick: 'Detik Lampu',
      lightsOutChime: 'Lonceng Lampu Padam',
      falseStartBuzz: 'Dengung Mula Salah',
      gameScreensCustomization: 'Penyesuaian Skrin Permainan',
      startScreen: 'Skrin Mula',
      resultScreen: 'Skrin Keputusan',
      startScreenVisualCanvasEditor: 'Editor Kanvas Visual Skrin Mula',
      openStartScreenEditor: 'Buka Editor Skrin Mula',
      resultScreenVisualCanvasEditor: 'Editor Kanvas Visual Skrin Keputusan',
      openResultScreenEditor: 'Buka Editor Skrin Keputusan',
      viewport: 'Port Pandang:',
      interactiveCanvasPreview: 'Pratonton Kanvas Berskala Interaktif (1024 × 576)',
    },
  },
  developer: {
    en: {
      editPrice: 'Edit Price',
      durationTiers: 'Duration Tiers',
      platformEvents: 'Platform Events',
      customOverrides: 'Custom Overrides',
      creditCoverage: 'Credit Coverage',
      durationPricingSimulator: 'Duration Pricing Simulator',
      eventPricingInventory: 'Event Pricing Inventory',
      searchEventOrOrg: 'Search event or organization...',
      saveEventPrice: 'Save Event Price',
      refreshAll: 'Refresh All',
      rewardPending: 'Reward Pending',
      approvedAndRewarded: 'Approved & Rewarded',
      publishedLive: 'Published Live',
      blockedByModeration: 'Blocked by Moderation',
      totalRewards: 'Total Rewards',
      syncQueue: 'Sync Queue',
      noRewardsPending: 'No Rewards Waiting for Approval',
      viewInspect: 'View / Inspect',
      rejectReward: 'Reject Reward',
      approveReward: 'Approve Reward',
      searchShowcase: 'Search event, org, client...',
      noShowcaseFound: 'No Showcase Submissions Found',
      unblockShowcase: 'Unblock Showcase',
      blockShowcase: 'Block Showcase',
      softDeleteShowcase: 'Soft Delete Showcase',
      gmailSettings: 'Gmail API Email Settings',
      sendTestEmail: 'Send Test Email',
      testEmailAddress: 'Recipient Email Address',
      errorLogsTitle: 'System Error Logs',
      clearLogs: 'Clear Logs',
      refreshLogs: 'Refresh Logs',
      severity: 'Severity',
      timestamp: 'Timestamp',
      noErrorsFound: 'No error logs found',
      organizationsTitle: 'Organizations Management',
      searchOrganizations: 'Search organizations...',
      members: 'Members',
      events: 'Events',
      owner: 'Owner',
      organizationDetail: 'Organization Detail',
      backToOrganizations: 'Back to Organizations',
      walletBalances: 'Wallet Balances',
      dangerZone: 'Danger Zone',
      themeNotFound: 'Theme Not Found',
      backToGameThemes: 'Back to Game Themes',
      saveSystemTheme: 'Save System Theme',
      savedToPlatform: 'Saved to Platform',
      testPlayLive: 'Test Play Live',
      newGame: 'Create New Game Engine',
      gameSlug: 'Game Slug',
      gameEngineType: 'Game Engine / Type',
    },
    zh: {
      editPrice: '修改价格',
      durationTiers: '时长定价档位',
      platformEvents: '全平台活动',
      customOverrides: '定制专属费率',
      creditCoverage: '积分抵扣上限',
      durationPricingSimulator: '时长计价模拟器',
      eventPricingInventory: '活动定价总账',
      searchEventOrOrg: '搜索活动或组织...',
      saveEventPrice: '保存活动价格',
      refreshAll: '全部刷新',
      rewardPending: '待审核奖励',
      approvedAndRewarded: '已审核并发放',
      publishedLive: '已公开发布',
      blockedByModeration: '已被审核封禁',
      totalRewards: '累计发放奖励',
      syncQueue: '同步审核队列',
      noRewardsPending: '当前暂无等待审核的奖励',
      viewInspect: '查看 / 详情检查',
      rejectReward: '拒绝发放奖励',
      approveReward: '批准发放奖励',
      searchShowcase: '搜索活动、组织或客户...',
      noShowcaseFound: '未找到案例展示提交',
      unblockShowcase: '解除展示封禁',
      blockShowcase: '封禁案例展示',
      softDeleteShowcase: '软删除案例展示',
      gmailSettings: 'Gmail API 邮件推送设置',
      sendTestEmail: '发送测试邮件',
      testEmailAddress: '收件人测试邮箱',
      errorLogsTitle: '系统异常日志',
      clearLogs: '清空日志',
      refreshLogs: '刷新日志',
      severity: '严重级别',
      timestamp: '时间戳',
      noErrorsFound: '当前暂无错误日志',
      organizationsTitle: '组织机构管理',
      searchOrganizations: '搜索组织名称、邮箱或ID...',
      members: '成员数',
      events: '活动数',
      owner: '所有者',
      organizationDetail: '组织机构详情',
      backToOrganizations: '返回组织列表',
      walletBalances: '钱包各资金池余额',
      dangerZone: '高风险操作区',
      themeNotFound: '未找到指定主题',
      backToGameThemes: '返回游戏主题列表',
      saveSystemTheme: '保存系统主题模板',
      savedToPlatform: '已成功保存至平台',
      testPlayLive: '实时试玩测试',
      newGame: '注册新游戏引擎',
      gameSlug: '游戏 URL Slug',
      gameEngineType: '游戏引擎类型',
    },
    ms: {
      editPrice: 'Edit Harga',
      durationTiers: 'Tahap Tempoh',
      platformEvents: 'Acara Platform',
      customOverrides: 'Pindaan Tersuai',
      creditCoverage: 'Liputan Kredit',
      durationPricingSimulator: 'Simulator Penetapan Harga Tempoh',
      eventPricingInventory: 'Inventori Harga Acara',
      searchEventOrOrg: 'Cari acara atau organisasi...',
      saveEventPrice: 'Simpan Harga Acara',
      refreshAll: 'Segarkan Semua',
      rewardPending: 'Ganjaran Belum Selesai',
      approvedAndRewarded: 'Diluluskan & Diganjari',
      publishedLive: 'Diterbitkan Langsung',
      blockedByModeration: 'Disekat oleh Moderasi',
      totalRewards: 'Jumlah Ganjaran',
      syncQueue: 'Segerakkan Baris Gilir',
      noRewardsPending: 'Tiada Ganjaran Menunggu Kelulusan',
      viewInspect: 'Lihat / Periksa',
      rejectReward: 'Tolak Ganjaran',
      approveReward: 'Luluskan Ganjaran',
      searchShowcase: 'Cari acara, org, pelanggan...',
      noShowcaseFound: 'Tiada Penyerahan Pameran Ditemui',
      unblockShowcase: 'Nyahsekat Pameran',
      blockShowcase: 'Sekat Pameran',
      softDeleteShowcase: 'Padam Lembut Pameran',
      gmailSettings: 'Tetapan E-mel Gmail API',
      sendTestEmail: 'Hantar E-mel Ujian',
      testEmailAddress: 'Alamat E-mel Penerima',
      errorLogsTitle: 'Log Ralat Sistem',
      clearLogs: 'Kosongkan Log',
      refreshLogs: 'Segarkan Log',
      severity: 'Keterukan',
      timestamp: 'Cap Masa',
      noErrorsFound: 'Tiada log ralat ditemui',
      organizationsTitle: 'Pengurusan Organisasi',
      searchOrganizations: 'Cari organisasi...',
      members: 'Ahli',
      events: 'Acara',
      owner: 'Pemilik',
      organizationDetail: 'Butiran Organisasi',
      backToOrganizations: 'Kembali ke Organisasi',
      walletBalances: 'Baki Dompet',
      dangerZone: 'Zon Bahaya',
      themeNotFound: 'Tema Tidak Ditemui',
      backToGameThemes: 'Kembali ke Tema Permainan',
      saveSystemTheme: 'Simpan Tema Sistem',
      savedToPlatform: 'Disimpan ke Platform',
      testPlayLive: 'Uji Main Langsung',
      newGame: 'Cipta Enjin Permainan Baharu',
      gameSlug: 'Slug Permainan',
      gameEngineType: 'Enjin / Jenis Permainan',
    },
  },
};

function injectNamespace(filePath: string, lang: 'en' | 'zh' | 'ms') {
  let content = fs.readFileSync(filePath, 'utf8');

  for (const [namespace, langMap] of Object.entries(translations)) {
    const keys = langMap[lang];
    if (!keys) continue;

    // Check if namespace exists
    const nsRegex = new RegExp(`(\\b${namespace}\\s*:\\s*\\{)`, 'g');
    const match = nsRegex.exec(content);

    if (match) {
      const insertPos = match.index + match[0].length;
      let newEntries = '';
      for (const [k, v] of Object.entries(keys)) {
        const checkKeyRegex = new RegExp(`\\b${k}\\s*:`);
        const namespaceBlock = content.slice(insertPos, content.indexOf('},', insertPos) + 1);
        if (!checkKeyRegex.test(namespaceBlock)) {
          const escapedVal = v.replace(/'/g, "\\'");
          newEntries += `\n    ${k}: '${escapedVal}',`;
        }
      }
      if (newEntries) {
        content = content.slice(0, insertPos) + newEntries + content.slice(insertPos);
      }
    } else {
      // Insert namespace right before the closing `};` of export const ...
      const lastClosing = content.lastIndexOf('};');
      if (lastClosing !== -1) {
        let nsBlock = `\n  ${namespace}: {`;
        for (const [k, v] of Object.entries(keys)) {
          const escapedVal = v.replace(/'/g, "\\'");
          nsBlock += `\n    ${k}: '${escapedVal}',`;
        }
        nsBlock += `\n  },\n`;
        content = content.slice(0, lastClosing) + nsBlock + content.slice(lastClosing);
      }
    }
  }

  fs.writeFileSync(filePath, content, 'utf8');
}

injectNamespace(enPath, 'en');
injectNamespace(zhPath, 'zh');
injectNamespace(msPath, 'ms');
console.log('Injected customizers and developer keys successfully.');
