import fs from 'fs';
import path from 'path';

const enPath = path.resolve('src/locales/en.ts');
const zhPath = path.resolve('src/locales/zh-CN.ts');
const msPath = path.resolve('src/locales/ms-MY.ts');

interface TranslationBundle {
  en: Record<string, string>;
  zh: Record<string, string>;
  ms: Record<string, string>;
}

export const additions: Record<string, TranslationBundle> = {
  studio: {
    en: {
      brandingGameTitlePlaceholder: 'e.g. CATCH THE BRAND, BRAND CAMPAIGN',
      brandingTaglinePlaceholder: 'e.g. Catch fresh fruits, avoid rotten hazards!',
      brandingDescriptionPlaceholder: 'Event activation notes, brand campaign info, or designer guidelines...',
      removeLogo: 'Remove Logo',
    },
    zh: {
      brandingGameTitlePlaceholder: '例如：品牌接接乐、夏季主题营销',
      brandingTaglinePlaceholder: '例如：抓取新鲜水果，避开腐烂障碍！',
      brandingDescriptionPlaceholder: '活动现场说明、品牌营销信息或设计师指南...',
      removeLogo: '移除品牌标识',
    },
    ms: {
      brandingGameTitlePlaceholder: 'cth. CATCH THE BRAND, KEMPEN JENAMA',
      brandingTaglinePlaceholder: 'cth. Tangkap buah-buahan segar, elak rintangan busuk!',
      brandingDescriptionPlaceholder: 'Nota pelancaran acara, info kempen jenama, atau panduan pereka...',
      removeLogo: 'Padam Logo Jenama',
    },
  },
  editor: {
    en: {
      xPos: 'X Pos',
      yPos: 'Y Pos',
      width: 'Width',
      height: 'Height',
      rotation: 'Rotation',
      opacity: 'Opacity',
      centerX: 'Center X',
      centerY: 'Center Y',
      relativeAlignment: 'Relative Alignment',
      containerCentering: 'Container Centering',
      horizontal: 'Horizontal',
      vertical: 'Vertical',
      layerStacking: 'Layer Stacking',
      front: 'Front',
      forward: 'Forward',
      backward: 'Backward',
      groupLayerControl: 'Group & Layer Control',
      ungroup: 'Ungroup',
      ungroupElements: 'Ungroup Elements',
      noChildren: 'No children',
      borderRadius: 'Border Radius',
      borderWidth: 'Border Width',
      borderColor: 'Border Color',
      backgroundColor: 'Background Color',
      backgroundImage: 'Background Image',
      darknessOverlay: 'Darkness Overlay',
      fontFamily: 'Font Family',
      fontSize: 'Font Size',
      buttonLabel: 'Button Label',
      actionTrigger: 'Action Trigger',
      exitGame: 'Exit Game',
      startGamePlay: 'Start Game / Play',
      openLeaderboard: 'Open Leaderboard',
      openRules: 'Open Rules / How to Play',
      openSettings: 'Open Settings',
      headerTitle: 'Header Title',
      description: 'Description',
      displayedRows: 'Displayed Rows',
      playerName: 'Player Name',
      score: 'Score',
      moves: 'Moves',
      accuracy: 'Accuracy',
      highlightCurrentPlayerRow: 'Highlight Current Player Row',
      baseFontSize: 'Base Font Size',
      cornerRadius: 'Corner Radius',
      header: 'Header',
      scores: 'Scores',
      inputPlaceholder: 'Input Placeholder',
      maxNameLength: 'Max Name Length',
      successMessage: 'Success Message',
      screenBackground: 'Screen Background',
      backgroundType: 'Background Type',
      uploadScreenWallpaper: 'Upload Screen Wallpaper',
      uploadNewImage: 'Upload New Image',
      imageUrl: 'Image URL',
      contentString: 'Content String',
      customLabel: 'Custom Label',
      layout: 'Layout',
      valueFontSize: 'Value Font Size',
      objectFit: 'Object Fit',
      metricType: 'Metric Type',
      roundsCount: 'Rounds Count',
      lightsCount: 'Lights Count',
      targetItem: 'Target Item',
      hazardItem: 'Hazard Item',
      customText: 'Custom Text',
      insertIntoCard: 'Insert Element into Card',
      insertIntoGroup: 'Insert Element into Group',
      startScreenCanvas: 'Start Screen Canvas',
      resultScreenCanvas: 'Result Screen Canvas',
      addElementsToCanvas: 'Add Elements to Canvas',
      clickToUpload: 'Click to upload',
      removeCustomImage: 'Remove custom image',
      orDragAndDrop: 'or drag and drop',
    },
    zh: {
      xPos: '横坐标 X',
      yPos: '纵坐标 Y',
      width: '宽度',
      height: '高度',
      rotation: '旋转角度',
      opacity: '不透明度',
      centerX: '水平居中',
      centerY: '垂直居中',
      relativeAlignment: '相对对齐方式',
      containerCentering: '容器内部居中',
      horizontal: '水平分布',
      vertical: '垂直分布',
      layerStacking: '图层层叠顺序',
      front: '置顶',
      forward: '上一层',
      backward: '下一层',
      groupLayerControl: '成组与图层管理',
      ungroup: '解散群组',
      ungroupElements: '拆分群组元素',
      noChildren: '无子元素',
      borderRadius: '圆角弧度',
      borderWidth: '边框粗细',
      borderColor: '边框颜色',
      backgroundColor: '背景颜色',
      backgroundImage: '背景图片',
      darknessOverlay: '暗色遮罩浓度',
      fontFamily: '字体系列',
      fontSize: '文字字号',
      buttonLabel: '按钮文本',
      actionTrigger: '触发动作',
      exitGame: '退出游戏',
      startGamePlay: '开始游戏',
      openLeaderboard: '打开排行榜',
      openRules: '玩法规则说明',
      openSettings: '打开设置',
      headerTitle: '标题文字',
      description: '描述说明',
      displayedRows: '展示榜单行数',
      playerName: '玩家昵称',
      score: '得分数值',
      moves: '翻牌步数',
      accuracy: '命中率',
      highlightCurrentPlayerRow: '高亮当前玩家排名',
      baseFontSize: '基础字号',
      cornerRadius: '边角圆弧',
      header: '榜单表头',
      scores: '得分列表',
      inputPlaceholder: '输入框提示词',
      maxNameLength: '昵称最大字数',
      successMessage: '成功提示语',
      screenBackground: '全屏画面背景',
      backgroundType: '背景填充类型',
      uploadScreenWallpaper: '上传定制壁纸',
      uploadNewImage: '上传新图片',
      imageUrl: '图片链接',
      contentString: '文本内容',
      customLabel: '自定义标签',
      layout: '排版方向',
      valueFontSize: '数值字号',
      objectFit: '图片适应模式',
      metricType: '指标类型',
      roundsCount: '轮次计数',
      lightsCount: '指示灯数',
      targetItem: '得分目标',
      hazardItem: '避让障碍',
      customText: '自定义文本',
      insertIntoCard: '置入卡片容器',
      insertIntoGroup: '置入群组容器',
      startScreenCanvas: '开始画面画布',
      resultScreenCanvas: '结算画面画布',
      addElementsToCanvas: '添加元素至画布',
      clickToUpload: '点击上传',
      removeCustomImage: '移除自定义图片',
      orDragAndDrop: '或拖拽图片至此处',
    },
    ms: {
      xPos: 'Posisi X',
      yPos: 'Posisi Y',
      width: 'Lebar',
      height: 'Tinggi',
      rotation: 'Putaran',
      opacity: 'Kelegapan',
      centerX: 'Pusat X',
      centerY: 'Pusat Y',
      relativeAlignment: 'Jajaran Relatif',
      containerCentering: 'Pusatkan Bekas',
      horizontal: 'Mendatar',
      vertical: 'Menegak',
      layerStacking: 'Susunan Lapisan',
      front: 'Paling Depan',
      forward: 'Ke Depan',
      backward: 'Ke Belakang',
      groupLayerControl: 'Kawalan Kumpulan & Lapisan',
      ungroup: 'Nyahkumpulan',
      ungroupElements: 'Nyahkumpul Elemen',
      noChildren: 'Tiada elemen anak',
      borderRadius: 'Jejari Sempadan',
      borderWidth: 'Ketebalan Sempadan',
      borderColor: 'Warna Sempadan',
      backgroundColor: 'Warna Latar Belakang',
      backgroundImage: 'Imej Latar Belakang',
      darknessOverlay: 'Lapisan Gelap',
      fontFamily: 'Keluarga Fon',
      fontSize: 'Saiz Fon',
      buttonLabel: 'Label Butang',
      actionTrigger: 'Tindakan Butang',
      exitGame: 'Keluar Permainan',
      startGamePlay: 'Mula Permainan / Main',
      openLeaderboard: 'Buka Papan Pendahulu',
      openRules: 'Buka Panduan / Peraturan',
      openSettings: 'Buka Tetapan',
      headerTitle: 'Tajuk Pengepala',
      description: 'Penerangan',
      displayedRows: 'Baris Dipaparkan',
      playerName: 'Nama Pemain',
      score: 'Skor',
      moves: 'Langkah',
      accuracy: 'Ketepatan',
      highlightCurrentPlayerRow: 'Sorot Baris Pemain Semasa',
      baseFontSize: 'Saiz Fon Asas',
      cornerRadius: 'Jejari Sudut',
      header: 'Pengepala',
      scores: 'Skor',
      inputPlaceholder: 'Pemegang Tempat Input',
      maxNameLength: 'Had Aksara Nama',
      successMessage: 'Mesej Kejayaan',
      screenBackground: 'Latar Belakang Skrin',
      backgroundType: 'Jenis Latar Belakang',
      uploadScreenWallpaper: 'Muat Naik Kertas Dinding Skrin',
      uploadNewImage: 'Muat Naik Imej Baharu',
      imageUrl: 'URL Imej',
      contentString: 'Kandungan Teks',
      customLabel: 'Label Tersuai',
      layout: 'Susun Atur',
      valueFontSize: 'Saiz Fon Nilai',
      objectFit: 'Kesesuaian Objek',
      metricType: 'Jenis Metrik',
      roundsCount: 'Bilangan Pusingan',
      lightsCount: 'Bilangan Lampu',
      targetItem: 'Item Sasaran',
      hazardItem: 'Item Bahaya',
      customText: 'Teks Tersuai',
      insertIntoCard: 'Masukkan Elemen ke Kad',
      insertIntoGroup: 'Masukkan Elemen ke Kumpulan',
      startScreenCanvas: 'Kanvas Skrin Mula',
      resultScreenCanvas: 'Kanvas Skrin Keputusan',
      addElementsToCanvas: 'Tambah Elemen ke Kanvas',
      clickToUpload: 'Klik untuk muat naik',
      removeCustomImage: 'Padam imej tersuai',
      orDragAndDrop: 'atau seret dan lepas',
    },
  },
  developer: {
    en: {
      gameNotFound: 'Game Not Found',
      noSystemThemesConfigured: 'No System Themes Configured',
      noCustomBackground: 'No Custom Background',
      rewardsLabel: 'Rewards',
      hazardsLabel: 'Hazards',
      unsetPrimaryDefaultTitle: 'Unset Primary Default?',
      contactEnquiryVars: 'Contact & Enquiry Variables',
      clientEnquiriesSubmissions: 'Client Enquiries & Form Submissions',
      noEnquiriesReceivedYet: 'No Enquiries Received Yet',
      publicSurfaceImpact: 'Public Surface Impact',
      reloadSettingsDatabase: 'Reload settings from database',
      viewInspect: 'View / Inspect',
      colMedia: 'Media',
      colReward: 'RM300 Reward',
      colVisibility: 'Visibility',
      colActions: 'Actions',
      approveRewardBtn: 'Approve Reward',
      sendCustomerInvitations: 'Send Customer Invitations',
      customerInvitationAuditLogs: 'Customer Invitation Audit Logs',
      deleteCustomerCompanyModalTitle: 'Delete Customer Company?',
      notesIndustry: 'Notes / Industry',
      colDateTime: 'Date / Time',
      colRecipientEmail: 'Recipient Email',
      colProvider: 'Provider',
      allTime: 'All Time',
      last24Hours: 'Last 24 Hours',
      last7Days: 'Last 7 Days',
      last30Days: 'Last 30 Days',
      colStatusTime: 'Status & Time',
      colCorrelationId: 'Request / Correlation ID',
      colMethodEndpoint: 'Method & Endpoint',
      colService: 'Service',
      colErrorMessage: 'Error Message / Type',
      copyStack: 'Copy Stack',
      copyJson: 'Copy JSON',
      walletLedgerBalances: 'Wallet & Ledger Balances',
      depositedCashBalance: 'Deposited cash balance',
      promotionalManualGrant: 'Promotional manual grant',
      showcaseReviewRewardDesc: 'RM300 review reward',
      depositBonusCredits: 'Deposit bonus credits',
      colMember: 'Member',
      colEmail: 'Email',
      colJoinedDate: 'Joined Date',
      colEventTitle: 'Event Title',
      colEventPrice: 'Event Price',
      colCreated: 'Created',
      colPublicLink: 'Public Link',
      sourceOfTruth: 'Source of Truth',
      colTypeDesc: 'Type / Description',
      colAmount: 'Amount',
      colBalanceAfter: 'Balance After',
      colReference: 'Reference',
      colTimestamp: 'Timestamp',
    },
    zh: {
      gameNotFound: '未找到游戏',
      noSystemThemesConfigured: '未配置系统官方主题',
      noCustomBackground: '无自定义背景图',
      rewardsLabel: '得分道具',
      hazardsLabel: '扣分障碍',
      unsetPrimaryDefaultTitle: '取消核心官方默认？',
      contactEnquiryVars: '联系与咨询配置参数',
      clientEnquiriesSubmissions: '客户咨询与表单提交记录',
      noEnquiriesReceivedYet: '暂未收到客户咨询',
      publicSurfaceImpact: '全平台前端影响范围',
      reloadSettingsDatabase: '从数据库重新加载设置',
      viewInspect: '查看与审核',
      colMedia: '媒体文件',
      colReward: 'RM300 奖励',
      colVisibility: '公开可见性',
      colActions: '操作',
      approveRewardBtn: '批准奖励',
      sendCustomerInvitations: '发送客户专属邀请',
      customerInvitationAuditLogs: '客户邀请审计日志',
      deleteCustomerCompanyModalTitle: '删除客户公司？',
      notesIndustry: '备注 / 行业分类',
      colDateTime: '日期 / 时间',
      colRecipientEmail: '接收邮箱',
      colProvider: '发送渠道',
      allTime: '全部时间',
      last24Hours: '最近 24 小时',
      last7Days: '最近 7 天',
      last30Days: '最近 30 天',
      colStatusTime: '状态与时间',
      colCorrelationId: '请求 / 关联追踪 ID',
      colMethodEndpoint: '请求方法与路由',
      colService: '服务模块',
      colErrorMessage: '错误信息与异常类型',
      copyStack: '复制堆栈',
      copyJson: '复制 JSON',
      walletLedgerBalances: '钱包与资金账本余额',
      depositedCashBalance: '充值现金余额',
      promotionalManualGrant: '促销奖励额度',
      showcaseReviewRewardDesc: 'RM300 案例展示审核奖励',
      depositBonusCredits: '充值赠送奖励点数',
      colMember: '成员姓名',
      colEmail: '邮箱',
      colJoinedDate: '加入日期',
      colEventTitle: '活动标题',
      colEventPrice: '活动授权金额',
      colCreated: '创建时间',
      colPublicLink: '公网访问链接',
      sourceOfTruth: '权威数据源',
      colTypeDesc: '类型与交易摘要',
      colAmount: '变动金额',
      colBalanceAfter: '变动后余额',
      colReference: '业务关联单号',
      colTimestamp: '时间戳',
    },
    ms: {
      gameNotFound: 'Permainan Tidak Ditemui',
      noSystemThemesConfigured: 'Tiada Tema Sistem Dikonfigurasikan',
      noCustomBackground: 'Tiada Latar Belakang Tersuai',
      rewardsLabel: 'Ganjaran',
      hazardsLabel: 'Bahaya',
      unsetPrimaryDefaultTitle: 'Nyahpilih Lalai Utama?',
      contactEnquiryVars: 'Pembolehubah Hubungi & Pertanyaan',
      clientEnquiriesSubmissions: 'Pertanyaan Klien & Penyerahan Borang',
      noEnquiriesReceivedYet: 'Tiada Pertanyaan Diterima Lagi',
      publicSurfaceImpact: 'Kesan Permukaan Awam',
      reloadSettingsDatabase: 'Muat semula tetapan dari pangkalan data',
      viewInspect: 'Lihat / Periksa',
      colMedia: 'Media',
      colReward: 'Ganjaran RM300',
      colVisibility: 'Keterlihatan',
      colActions: 'Tindakan',
      approveRewardBtn: 'Luluskan Ganjaran',
      sendCustomerInvitations: 'Hantar Jemputan Pelanggan',
      customerInvitationAuditLogs: 'Log Audit Jemputan Pelanggan',
      deleteCustomerCompanyModalTitle: 'Padam Syarikat Pelanggan?',
      notesIndustry: 'Nota / Industri',
      colDateTime: 'Tarikh / Masa',
      colRecipientEmail: 'E-mel Penerima',
      colProvider: 'Penyedia',
      allTime: 'Sepanjang Masa',
      last24Hours: '24 Jam Terakhir',
      last7Days: '7 Hari Terakhir',
      last30Days: '30 Hari Terakhir',
      colStatusTime: 'Status & Masa',
      colCorrelationId: 'ID Permintaan / Korelasi',
      colMethodEndpoint: 'Kaedah & Titik Akhir',
      colService: 'Perkhidmatan',
      colErrorMessage: 'Mesej Ralat / Jenis',
      copyStack: 'Salin Tindanan',
      copyJson: 'Salin JSON',
      walletLedgerBalances: 'Baki Dompet & Lejar',
      depositedCashBalance: 'Baki tunai didepositkan',
      promotionalManualGrant: 'Pemberian manual promosi',
      showcaseReviewRewardDesc: 'Ganjaran ulasan RM300',
      depositBonusCredits: 'Kredit bonus deposit',
      colMember: 'Ahli',
      colEmail: 'E-mel',
      colJoinedDate: 'Tarikh Sertai',
      colEventTitle: 'Tajuk Acara',
      colEventPrice: 'Harga Acara',
      colCreated: 'Dicipta',
      colPublicLink: 'Pautan Awam',
      sourceOfTruth: 'Sumber Kebenaran',
      colTypeDesc: 'Jenis / Penerangan',
      colAmount: 'Jumlah',
      colBalanceAfter: 'Baki Selepas',
      colReference: 'Rujukan',
      colTimestamp: 'Cap Masa',
    },
  },
};

function injectBundle(filePath: string, lang: 'en' | 'zh' | 'ms') {
  let content = fs.readFileSync(filePath, 'utf8');

  for (const [namespace, bundle] of Object.entries(additions)) {
    const keys = bundle[lang];
    const nsRegex = new RegExp(`(\\s*${namespace}:\\s*\\{[\\s\\S]*?\\n\\s*\\})`, 'm');
    const match = content.match(nsRegex);

    if (match && match[0]) {
      let block = match[0];
      // strip closing }
      const lastBraceIndex = block.lastIndexOf('}');
      let newEntries = '';
      for (const [k, v] of Object.entries(keys)) {
        // Only inject if key does not already exist in block
        if (!block.includes(`${k}:`)) {
          const escaped = v.replace(/'/g, "\\'");
          newEntries += `    ${k}: '${escaped}',\n`;
        }
      }
      if (newEntries.length > 0) {
        const updatedBlock = block.slice(0, lastBraceIndex) + newEntries + block.slice(lastBraceIndex);
        content = content.replace(block, updatedBlock);
      }
    }
  }

  fs.writeFileSync(filePath, content, 'utf8');
}

injectBundle(enPath, 'en');
injectBundle(zhPath, 'zh');
injectBundle(msPath, 'ms');
console.log('Final batch keys successfully injected into en, zh-CN, ms-MY.');
