import fs from 'fs';
import path from 'path';

const enPath = path.resolve('src/locales/en.ts');
const zhPath = path.resolve('src/locales/zh-CN.ts');
const msPath = path.resolve('src/locales/ms-MY.ts');

interface TranslationBundle {
  en: Record<string, string>;
  zh: Record<string, string>;
  ms: Record<string, string>;
}

export const additions: Record<string, TranslationBundle> = {
  studio: {
    en: {
      multiGameCatalogTitle: 'Multi-Game Platform Catalog',
      multiGameCatalogDesc: 'Available interactive game engines registered by Developer / Admin',
      loadingPlatformGames: 'Loading registered platform games...',
      resetAllLayoutTitle: 'Reset all element coordinates to factory defaults',
      resetElementPosition: 'Reset this element to default position',
      alignLeftPct: '0% (Left)',
      alignCenterPct: '50% (Center)',
      alignRightPct: '100% (Right)',
      alignTopPct: '0% (Top)',
      alignMiddlePct: '50% (Center)',
      alignBottomPct: '100% (Bottom)',
      exitFullscreen: 'Exit Fullscreen',
      testingInteractive: 'Testing (Interactive)',
      autoDemo: 'Auto Demo',
      systemThemesReadOnlyNotice: 'System themes are read-only templates. To customize images, items, scoring, and branding, click Clone to add a copy to My Themes.',
      formulaReflex: 'Formula Reflex',
    },
    zh: {
      multiGameCatalogTitle: '多款互动游戏平台目录',
      multiGameCatalogDesc: '由开发者 / 管理员注册的可用互动游戏引擎',
      loadingPlatformGames: '正在加载已注册的平台游戏...',
      resetAllLayoutTitle: '将所有元素坐标重置为出厂默认设置',
      resetElementPosition: '将此元素重置为默认位置',
      alignLeftPct: '0% (居左)',
      alignCenterPct: '50% (居中)',
      alignRightPct: '100% (居右)',
      alignTopPct: '0% (顶部)',
      alignMiddlePct: '50% (居中)',
      alignBottomPct: '100% (底部)',
      exitFullscreen: '退出全屏',
      testingInteractive: '测试操作 (交互模式)',
      autoDemo: '自动演示',
      systemThemesReadOnlyNotice: '系统官方主题为只读模板。如需自定义图片、道具、得分和品牌标识，请点击“克隆”将其复制到“我的主题”中。',
      formulaReflex: 'F1 极速反应',
    },
    ms: {
      multiGameCatalogTitle: 'Katalog Platform Pelbagai Permainan',
      multiGameCatalogDesc: 'Enjin permainan interaktif tersedia yang didaftarkan oleh Pembangun / Pentadbir',
      loadingPlatformGames: 'Sedang memuatkan permainan platform yang didaftarkan...',
      resetAllLayoutTitle: 'Tetapkan semula semua koordinat elemen ke lalai kilang',
      resetElementPosition: 'Tetapkan semula elemen ini ke kedudukan lalai',
      alignLeftPct: '0% (Kiri)',
      alignCenterPct: '50% (Tengah)',
      alignRightPct: '100% (Kanan)',
      alignTopPct: '0% (Atas)',
      alignMiddlePct: '50% (Tengah)',
      alignBottomPct: '100% (Bawah)',
      exitFullscreen: 'Keluar Skrin Penuh',
      testingInteractive: 'Ujian (Interaktif)',
      autoDemo: 'Demo Automatik',
      systemThemesReadOnlyNotice: 'Tema sistem ialah templat baca sahaja. Untuk menyesuaikan imej, item, skor dan penjenamaan, klik Klon untuk menambah salinan ke Tema Saya.',
      formulaReflex: 'Refleks Formula',
    },
  },
  game: {
    en: {
      noScoresYetTitle: 'No Scores Yet!',
      highScores: 'High Scores',
    },
    zh: {
      noScoresYetTitle: '暂无高分记录！',
      highScores: '高分榜',
    },
    ms: {
      noScoresYetTitle: 'Belum Ada Skor!',
      highScores: 'Skor Tertinggi',
    },
  },
  developer: {
    en: {
      platformDefaultBasePrice: 'Platform Default Base Price (1 Day)',
      platformDefaultBasePriceDesc: 'Authoritative base price fallback applied to 1-day events across all organizations',
      editBase: 'Edit Base',
      calendarDay: '/ 1 calendar day',
      serverAuthSetting: 'Server-authoritative database setting',
      lastUpdatedDate: 'Last updated: {{date}}',
      activeTierRules: 'Active tier rules',
      acrossAllOrgs: 'Across all orgs',
      adminCustomRates: 'Admin custom rates',
      topUpBonusMax: 'Top-up bonus max',
      durationBasedPricingTiers: 'Duration-Based Pricing Tiers',
      addDurationTier: 'Add Duration Tier',
      durationRange: 'Duration Range',
      minDaysHeader: 'Min Days',
      maxDaysHeader: 'Max Days',
      authoritativePrice: 'Authoritative Price',
      dailyEquivalent: 'Daily Equivalent',
      editTier: 'Edit Tier',
      deleteTier: 'Delete Tier',
      calculatedDuration: 'Calculated Duration:',
      simulatedQuote: 'Simulated Quote:',
      allPricingTypes: 'All Pricing Types',
      customOverridesOnly: 'Custom Overrides Only',
      standardTiersOnly: 'Standard Tiers Only',
      allStatuses: 'All Event & Payment Statuses',
      eventDraft: 'Event: DRAFT',
      eventLive: 'Event: LIVE',
      eventCompleted: 'Event: COMPLETED',
      eventCancelled: 'Event: CANCELLED',
      paymentPaid: 'Payment: PAID',
      paymentUnpaid: 'Payment: UNPAID',
      loadingEventPricing: 'Loading event pricing ledger...',
      noEventsFound: 'No events found',
      adjustSearchOrFilters: 'Try adjusting your search or filters.',
      eventName: 'Event Name',
      durationAndDates: 'Duration & Dates',
      effectivePrice: 'Effective Price',
      pricingStatus: 'Pricing Status',
      eventStatus: 'Event Status',
      paymentStatus: 'Payment Status',
      pendingQuote: 'Pending Quote',
      reactivateEvent: 'Manually override status & reactivate event',
      configureDayRange: 'Configure day range and fixed rate',
      editEventPriceTitle: 'Edit Event Price',
      currentEffectivePrice: 'Current Effective Price:',
      savingPrice: 'Saving Price...',
      savingBase: 'Saving Base...',
      savePlatformBase: 'Save Platform Base',
      saveEventPriceBtn: 'Save Event Price',
      orgLabel: 'Org:',
      devAdminPlatform: 'DevAdmin Platform',
      devPlatformFooter: 'Brand Engagement Games Platform • Developer Administration Architecture',
      refreshPendingRewardQueue: 'Refresh Pending Reward Queue',
      checkingPendingRewards: 'Checking pending reward approvals...',
      noRewardsWaiting: 'No Rewards Waiting for Approval',
      ownerLabel: 'Owner:',
      publishedLabel: 'Published:',
      mediaLabel: 'Media:',
      inspectShowcaseDetails: 'Inspect showcase details, media, and description',
      rejectRewardBtn: 'Reject Reward',
      approveRM300Btn: 'Approve RM300',
      loadingSubmissions: 'Loading showcase submissions...',
      noSubmissionsFound: 'No Showcase Submissions Found',
      showcaseAndEvent: 'Showcase & Event',
      organizationAndClient: 'Organization & Client',
      mediaHeader: 'Media',
      createdPublished: 'Created / Published',
      rm300Reward: 'RM300 Reward',
      visibilityHeader: 'Visibility',
      noClientSpecified: 'No client specified',
      rm300Granted: 'RM300 Granted',
      openPublicShowcaseNewTab: 'Open Public Showcase in New Tab',
      sharePublicShowcaseUrl: 'Share Public Showcase URL',
      linkCopied: 'Link copied',
      blockShowcaseTitle: 'Block Showcase (Hide Publicly)',
      unblockShowcaseTitle: 'Unblock Showcase (Restore Public Access)',
      adminSoftDelete: 'Admin Soft Delete Showcase',
      approveOwnerRewardTitle: 'Approve Owner First-Event Reward',
      ownerRewardExecution: 'Owner-Level Reward Execution',
      rejectFirstEventRewardTitle: 'Reject First-Event Showcase Reward',
      rejectFeedbackPlaceholder: 'e.g. Please provide at least 3 high-resolution photos of the booth activation and ensure the client logo is transparent.',
      showcaseBlockedNotice: 'Showcase Blocked by Moderation',
      reasonLabel: 'Reason:',
      showcaseSoftDeletedNotice: 'Showcase Administratively Soft-Deleted',
      loadingGalleryItems: 'Loading gallery items...',
      openOriginal: 'Open original',
      auditInfo: 'Audit Information:',
      blockShowcaseModalTitle: 'Block Showcase',
      blockReasonPlaceholder: 'e.g. Contains sensitive client proprietary assets, or violates community guidelines.',
      unblockShowcaseModalTitle: 'Unblock Showcase',
      unblockReasonPlaceholder: 'e.g. Sensitive assets reviewed and cleared with event organizer.',
      softDeleteModalTitle: 'Soft Delete Showcase',
      softDeleteReasonPlaceholder: 'e.g. Inappropriate content, copyright infringement, or spam.',
      welcomeShowcaseTopupCredits: 'Welcome + Showcase + Top-up credits',
      totalWalletValue: 'Total Wallet Value',
      searchOrgsFullPlaceholder: 'Search by organization name, owner name, owner email, or slug...',
      loadingOrgsAndLedgers: 'Loading organizations & wallet ledgers...',
      noOrgsFound: 'No organizations found',
      paidBalance: 'Paid Balance',
      eventCredit: 'Event Credit',
      totalValue: 'Total Value',
      exportJson: 'Export JSON',
      noLogsRecorded: 'No API errors recorded',
      noLogsRecordedDesc: 'No errors match the current filters or no operational errors have occurred.',
      gameEngineNotFound: 'Game engine not found',
      backToGamesList: 'Back to Game Catalog',
      gameMetadataAndSettings: 'Game Metadata & Settings',
      systemThemes: 'System Themes',
      gamePricingTiers: 'Duration Pricing Tiers',
      livePlaytest: 'Interactive Live Playtest',
      contactInquiriesTitle: 'Contact Enquiries & Support Messages',
      contactInquiriesDesc: 'Review inbound contact inquiries, sales leads, and support messages from prospective clients.',
      allInquiries: 'All Enquiries',
      pendingInquiries: 'Pending',
      resolvedInquiries: 'Resolved',
      archivedInquiries: 'Archived',
      searchInquiriesPlaceholder: 'Search by name, email, company, or message content...',
      loadingInquiries: 'Loading contact enquiries...',
      noInquiriesFound: 'No contact enquiries found',
      noInquiriesFoundDesc: 'No inbound enquiries match the selected filters.',
      gmailIntegrationDesc: 'Platform-wide dedicated Google Workspace sending account used for system receipts, notifications, and customer invites.',
      newSystemDefaultTheme: 'New System Default Theme',
      themeNamePresetPlaceholder: 'e.g. Christmas Catch, Neon Cyber Rush',
      themeDescriptionPlaceholder: 'Visual narrative and description for this theme preset...',
      setAsPrimaryDefault: 'Set as primary default theme',
      registerNewGameModalTitle: 'Register New Platform Game',
    },
    zh: {
      platformDefaultBasePrice: '平台默认基础单价 (1 天)',
      platformDefaultBasePriceDesc: '适用于所有组织 1 天活动的权威基础兜底价格',
      editBase: '编辑基准价',
      calendarDay: '/ 1 个日历日',
      serverAuthSetting: '服务器权威数据库配置',
      lastUpdatedDate: '最后更新于：{{date}}',
      activeTierRules: '活跃阶梯规则',
      acrossAllOrgs: '跨所有组织',
      adminCustomRates: '管理员特调费率',
      topUpBonusMax: '充值奖励上限',
      durationBasedPricingTiers: '按天数阶梯计价规则',
      addDurationTier: '添加天数阶梯',
      durationRange: '活动天数范围',
      minDaysHeader: '最少天数',
      maxDaysHeader: '最多天数',
      authoritativePrice: '权威结算价',
      dailyEquivalent: '日均折合单价',
      editTier: '编辑阶梯',
      deleteTier: '删除阶梯',
      calculatedDuration: '计算活动天数：',
      simulatedQuote: '模拟结算报价：',
      allPricingTypes: '全部计价类型',
      customOverridesOnly: '仅自定义特调价',
      standardTiersOnly: '仅标准阶梯价',
      allStatuses: '全部活动与支付状态',
      eventDraft: '活动：草稿 (DRAFT)',
      eventLive: '活动：进行中 (LIVE)',
      eventCompleted: '活动：已结束 (COMPLETED)',
      eventCancelled: '活动：已取消 (CANCELLED)',
      paymentPaid: '支付：已支付 (PAID)',
      paymentUnpaid: '支付：未支付 (UNPAID)',
      loadingEventPricing: '正在加载活动定价账本...',
      noEventsFound: '未找到相关活动',
      adjustSearchOrFilters: '请尝试调整您的搜索关键字或筛选条件。',
      eventName: '活动名称',
      durationAndDates: '天数与档期',
      effectivePrice: '实际生效价格',
      pricingStatus: '计价类型',
      eventStatus: '活动状态',
      paymentStatus: '支付状态',
      pendingQuote: '待结算报价',
      reactivateEvent: '手动覆盖状态并重新激活活动',
      configureDayRange: '配置天数范围与固定费率',
      editEventPriceTitle: '编辑活动价格',
      currentEffectivePrice: '当前生效价格：',
      savingPrice: '正在保存价格...',
      savingBase: '正在保存基准价...',
      savePlatformBase: '保存平台基准价',
      saveEventPriceBtn: '保存活动价格',
      orgLabel: '组织：',
      devAdminPlatform: '开发者管理平台',
      devPlatformFooter: '品牌互动游戏平台 • 开发者管理架构体系',
      refreshPendingRewardQueue: '刷新待审批奖励队列',
      checkingPendingRewards: '正在检查待审批的展示案例奖励...',
      noRewardsWaiting: '当前没有待审批的展示案例奖励',
      ownerLabel: '所有者：',
      publishedLabel: '发布时间：',
      mediaLabel: '媒体：',
      inspectShowcaseDetails: '查看展示案例详情、媒体与文案',
      rejectRewardBtn: '驳回奖励',
      approveRM300Btn: '批准 RM300',
      loadingSubmissions: '正在加载案例提交记录...',
      noSubmissionsFound: '未找到案例提交记录',
      showcaseAndEvent: '案例与关联活动',
      organizationAndClient: '组织与客户',
      mediaHeader: '媒体资源',
      createdPublished: '创建 / 发布时间',
      rm300Reward: 'RM300 奖励状态',
      visibilityHeader: '公开可见性',
      noClientSpecified: '未指定客户',
      rm300Granted: '已发放 RM300',
      openPublicShowcaseNewTab: '在新标签页打开公开案例展示',
      sharePublicShowcaseUrl: '分享公开案例链接',
      linkCopied: '链接已复制',
      blockShowcaseTitle: '屏蔽案例（设为隐藏）',
      unblockShowcaseTitle: '解除屏蔽（恢复公开访问）',
      adminSoftDelete: '管理员软删除案例',
      approveOwnerRewardTitle: '批准所有者首场活动奖励',
      ownerRewardExecution: '所有者层级奖励发放',
      rejectFirstEventRewardTitle: '驳回首场活动案例奖励',
      rejectFeedbackPlaceholder: '例如：请提供至少3张展位活动的高清现场照片，并确保客户Logo使用透明背景。',
      showcaseBlockedNotice: '该案例已被内容审核团队屏蔽',
      reasonLabel: '原因：',
      showcaseSoftDeletedNotice: '该案例已被管理员软删除',
      loadingGalleryItems: '正在加载图库媒体...',
      openOriginal: '查看原图',
      auditInfo: '审核日志信息：',
      blockShowcaseModalTitle: '屏蔽案例展示',
      blockReasonPlaceholder: '例如：包含客户未经授权的机密资产，或违反社区规范。',
      unblockShowcaseModalTitle: '解除案例屏蔽',
      unblockReasonPlaceholder: '例如：敏感资产已与活动主办方核实并得到授权许可。',
      softDeleteModalTitle: '软删除案例展示',
      softDeleteReasonPlaceholder: '例如：不合规内容、侵犯版权或垃圾营销。',
      welcomeShowcaseTopupCredits: '新手福利 + 案例奖励 + 充值赠金',
      totalWalletValue: '钱包总净值',
      searchOrgsFullPlaceholder: '按组织名称、所有者姓名、所有者邮箱或别名搜索...',
      loadingOrgsAndLedgers: '正在加载组织与钱包总账...',
      noOrgsFound: '未找到任何组织',
      paidBalance: '现金实付余额',
      eventCredit: '活动抵扣金',
      totalValue: '总价值',
      exportJson: '导出 JSON',
      noLogsRecorded: '暂无记录的 API 错误',
      noLogsRecordedDesc: '当前筛选条件下没有错误，或系统运行良好无异常。',
      gameEngineNotFound: '未找到该游戏引擎',
      backToGamesList: '返回游戏目录',
      gameMetadataAndSettings: '游戏元数据与基础配置',
      systemThemes: '系统官方主题',
      gamePricingTiers: '天数计价阶梯',
      livePlaytest: '实时互动试玩测试',
      contactInquiriesTitle: '联络咨询与支持留言',
      contactInquiriesDesc: '查看来自意向客户的商务咨询、销售线索与技术支持留言。',
      allInquiries: '全部留言',
      pendingInquiries: '待处理',
      resolvedInquiries: '已解决',
      archivedInquiries: '已归档',
      searchInquiriesPlaceholder: '按姓名、邮箱、公司或留言内容搜索...',
      loadingInquiries: '正在加载联络留言...',
      noInquiriesFound: '未找到联络留言',
      noInquiriesFoundDesc: '没有符合所选筛选条件的留言记录。',
      gmailIntegrationDesc: '平台专用的 Google Workspace 发件账户，用于发送系统收据、通知及企业客户邀请。',
      newSystemDefaultTheme: '新建系统官方默认主题',
      themeNamePresetPlaceholder: '例如：圣诞欢捕、赛博幻影、夏日狂欢',
      themeDescriptionPlaceholder: '此主题预设的视觉叙事与设计说明...',
      setAsPrimaryDefault: '设为核心官方默认主题',
      registerNewGameModalTitle: '注册新平台游戏引擎',
    },
    ms: {
      platformDefaultBasePrice: 'Harga Asas Lalai Platform (1 Hari)',
      platformDefaultBasePriceDesc: 'Harga asas berwibawa sandaran dikenakan pada acara 1 hari merentas semua organisasi',
      editBase: 'Edit Harga Asas',
      calendarDay: '/ 1 hari kalendar',
      serverAuthSetting: 'Tetapan pangkalan data berwibawa pelayan',
      lastUpdatedDate: 'Kemas kini terakhir: {{date}}',
      activeTierRules: 'Peraturan peringkat aktif',
      acrossAllOrgs: 'Merentas semua organisasi',
      adminCustomRates: 'Kadar tersuai pentadbir',
      topUpBonusMax: 'Maksimum bonus tambah nilai',
      durationBasedPricingTiers: 'Peringkat Harga Berasaskan Tempoh',
      addDurationTier: 'Tambah Peringkat Tempoh',
      durationRange: 'Julat Tempoh',
      minDaysHeader: 'Hari Min',
      maxDaysHeader: 'Hari Maks',
      authoritativePrice: 'Harga Berwibawa',
      dailyEquivalent: 'Setara Harian',
      editTier: 'Edit Peringkat',
      deleteTier: 'Padam Peringkat',
      calculatedDuration: 'Tempoh Dikira:',
      simulatedQuote: 'Sebut Harga Simulasi:',
      allPricingTypes: 'Semua Jenis Harga',
      customOverridesOnly: 'Gantian Tersuai Sahaja',
      standardTiersOnly: 'Peringkat Standard Sahaja',
      allStatuses: 'Semua Status Acara & Bayaran',
      eventDraft: 'Acara: DRAF',
      eventLive: 'Acara: LANGSUNG',
      eventCompleted: 'Acara: SELESAI',
      eventCancelled: 'Acara: DIBATALKAN',
      paymentPaid: 'Bayaran: DIBAYAR',
      paymentUnpaid: 'Bayaran: BELUM DIBAYAR',
      loadingEventPricing: 'Sedang memuatkan lejar harga acara...',
      noEventsFound: 'Tiada acara ditemui',
      adjustSearchOrFilters: 'Cuba sesuaikan carian atau penapis anda.',
      eventName: 'Nama Acara',
      durationAndDates: 'Tempoh & Tarikh',
      effectivePrice: 'Harga Berkesan',
      pricingStatus: 'Status Harga',
      eventStatus: 'Status Acara',
      paymentStatus: 'Status Bayaran',
      pendingQuote: 'Sebut Harga Belum Selesai',
      reactivateEvent: 'Ganti status secara manual & aktifkan semula acara',
      configureDayRange: 'Konfigurasikan julat hari dan kadar tetap',
      editEventPriceTitle: 'Edit Harga Acara',
      currentEffectivePrice: 'Harga Berkesan Semasa:',
      savingPrice: 'Sedang Menyimpan Harga...',
      savingBase: 'Sedang Menyimpan Asas...',
      savePlatformBase: 'Simpan Asas Platform',
      saveEventPriceBtn: 'Simpan Harga Acara',
      orgLabel: 'Org:',
      devAdminPlatform: 'Platform Pentadbir Dev',
      devPlatformFooter: 'Platform Permainan Penglibatan Jenama • Seni Bina Pentadbiran Pembangun',
      refreshPendingRewardQueue: 'Segarkan Baris Gilir Ganjaran Belum Selesai',
      checkingPendingRewards: 'Sedang memeriksa kelulusan ganjaran belum selesai...',
      noRewardsWaiting: 'Tiada Ganjaran Menunggu Kelulusan',
      ownerLabel: 'Pemilik:',
      publishedLabel: 'Diterbitkan:',
      mediaLabel: 'Media:',
      inspectShowcaseDetails: 'Periksa butiran pameran, media dan penerangan',
      rejectRewardBtn: 'Tolak Ganjaran',
      approveRM300Btn: 'Luluskan RM300',
      loadingSubmissions: 'Sedang memuatkan penyerahan pameran...',
      noSubmissionsFound: 'Tiada Penyerahan Pameran Ditemui',
      showcaseAndEvent: 'Pameran & Acara',
      organizationAndClient: 'Organisasi & Pelanggan',
      mediaHeader: 'Media',
      createdPublished: 'Dicipta / Diterbitkan',
      rm300Reward: 'Ganjaran RM300',
      visibilityHeader: 'Keterlihatan',
      noClientSpecified: 'Tiada pelanggan dinyatakan',
      rm300Granted: 'RM300 Diberikan',
      openPublicShowcaseNewTab: 'Buka Pameran Awam dalam Tab Baharu',
      sharePublicShowcaseUrl: 'Kongsi URL Pameran Awam',
      linkCopied: 'Pautan disalin',
      blockShowcaseTitle: 'Sekat Pameran (Sembunyikan Secara Awam)',
      unblockShowcaseTitle: 'Nyahsekat Pameran (Pulihkan Akses Awam)',
      adminSoftDelete: 'Padam Lembut Pameran oleh Pentadbir',
      approveOwnerRewardTitle: 'Luluskan Ganjaran Acara Pertama Pemilik',
      ownerRewardExecution: 'Pelaksanaan Ganjaran Peringkat Pemilik',
      rejectFirstEventRewardTitle: 'Tolak Ganjaran Pameran Acara Pertama',
      rejectFeedbackPlaceholder: 'cth. Sila berikan sekurang-kurangnya 3 foto resolusi tinggi pengaktifan gerai dan pastikan logo pelanggan adalah telus.',
      showcaseBlockedNotice: 'Pameran Disekat oleh Moderasi',
      reasonLabel: 'Sebab:',
      showcaseSoftDeletedNotice: 'Pameran Dipadamkan secara Lembut oleh Pentadbir',
      loadingGalleryItems: 'Sedang memuatkan item galeri...',
      openOriginal: 'Buka asal',
      auditInfo: 'Maklumat Audit:',
      blockShowcaseModalTitle: 'Sekat Pameran',
      blockReasonPlaceholder: 'cth. Mengandungi aset proprietari pelanggan yang sensitif, atau melanggar garis panduan komuniti.',
      unblockShowcaseModalTitle: 'Nyahsekat Pameran',
      unblockReasonPlaceholder: 'cth. Aset sensitif telah disemak dan diselesaikan bersama penganjur acara.',
      softDeleteModalTitle: 'Padam Lembut Pameran',
      softDeleteReasonPlaceholder: 'cth. Kandungan tidak sesuai, pelanggaran hak cipta atau spam.',
      welcomeShowcaseTopupCredits: 'Kredit Selamat Datang + Pameran + Tambah Nilai',
      totalWalletValue: 'Jumlah Nilai Dompet',
      searchOrgsFullPlaceholder: 'Cari mengikut nama organisasi, nama pemilik, e-mel pemilik atau slug...',
      loadingOrgsAndLedgers: 'Sedang memuatkan organisasi & lejar dompet...',
      noOrgsFound: 'Tiada organisasi ditemui',
      paidBalance: 'Baki Berbayar',
      eventCredit: 'Kredit Acara',
      totalValue: 'Jumlah Nilai',
      exportJson: 'Eksport JSON',
      noLogsRecorded: 'Tiada ralat API direkodkan',
      noLogsRecordedDesc: 'Tiada ralat yang sepadan dengan penapis semasa atau tiada ralat operasi berlaku.',
      gameEngineNotFound: 'Enjin permainan tidak ditemui',
      backToGamesList: 'Kembali ke Katalog Permainan',
      gameMetadataAndSettings: 'Metadata & Tetapan Permainan',
      systemThemes: 'Tema Sistem',
      gamePricingTiers: 'Peringkat Harga Tempoh',
      livePlaytest: 'Ujian Main Langsung Interaktif',
      contactInquiriesTitle: 'Pertanyaan Hubungi & Mesej Sokongan',
      contactInquiriesDesc: 'Semak pertanyaan hubungan masuk, petunjuk jualan, dan mesej sokongan daripada bakal pelanggan.',
      allInquiries: 'Semua Pertanyaan',
      pendingInquiries: 'Belum Selesai',
      resolvedInquiries: 'Diselesaikan',
      archivedInquiries: 'Diarkibkan',
      searchInquiriesPlaceholder: 'Cari mengikut nama, e-mel, syarikat atau kandungan mesej...',
      loadingInquiries: 'Sedang memuatkan pertanyaan hubungan...',
      noInquiriesFound: 'Tiada pertanyaan hubungan ditemui',
      noInquiriesFoundDesc: 'Tiada pertanyaan masuk yang sepadan dengan penapis yang dipilih.',
      gmailIntegrationDesc: 'Akaun penghantaran Google Workspace khusus seluruh platform yang digunakan untuk resit sistem, pemberitahuan dan jemputan pelanggan.',
      newSystemDefaultTheme: 'Tema Lalai Sistem Baharu',
      themeNamePresetPlaceholder: 'cth. Tangkapan Krismas, Larian Siber Neon',
      themeDescriptionPlaceholder: 'Naratif visual dan penerangan untuk pratetap tema ini...',
      setAsPrimaryDefault: 'Tetapkan sebagai tema lalai utama',
      registerNewGameModalTitle: 'Daftar Permainan Platform Baharu',
    },
  },
  editor: {
    en: {
      startScreenBg: 'Start Screen Background',
      resultScreenBg: 'Result Screen Background',
      activeThemeBg: 'Active Theme BG',
      activeThemeBgDesc: 'Uses theme wallpaper',
      solidColor: 'Solid Color',
      solidColorDesc: 'Custom backdrop color',
      customImage: 'Custom Image',
      customImageDesc: 'Independent artwork upload',
      customColor: 'Custom Color',
      customStartBgLoaded: 'Custom Start Screen Background Loaded',
      aspectRatio16_9: '16:9 recommended aspect ratio (1024×576px or higher)',
      replaceImage: 'Replace Image',
      supportsPngJpgWebp: 'Supports PNG, JPG, WebP (Max 10MB)',
      darkBackdropOverlay: 'Dark Backdrop Overlay',
      startElementVisibility: 'Start Screen Element Visibility',
      headerLogoEyebrow: 'Header Eyebrow / Logo',
      headerLogoEyebrowDesc: 'Top arcade badge or brand logo',
      rulesCollectiblesCards: 'Rules & Collectibles Cards',
      rulesCollectiblesCardsDesc: 'Shows target (+10) and hazard (-10)',
      keyboardHintsPill: 'Keyboard Hints Pill',
      keyboardHintsPillDesc: 'Shows Arrow & A/D controls',
      leaderboardBtn: 'Leaderboard Button',
      leaderboardBtnDesc: 'Shortcut button to scores',
      howToPlayBtn: 'How-To-Play Guide Button',
      howToPlayBtnDesc: 'Help modal button in footer',
      gameHeaderIcon: 'Game Header Icon',
      gameHeaderIconDesc: 'Grid symbol badge at the top',
      gridDimensionsPill: 'Grid Dimensions Pill',
      pairsCountPill: 'Pairs Count Pill',
      timerDurationPill: 'Timer Duration Pill',
      startingGantryIcon: 'Starting Gantry Icon',
      startingGantryIconDesc: 'Top reaction zap symbol',
      roundsCountPill: 'Rounds Count Pill',
      gantryLightsPill: 'Gantry Lights Pill',
      activeAndReady: 'Active & Ready',
      dragAndDrop: 'or drag and drop',
      bgOverlayDimming: 'Background Overlay Dimming',
      resultTextLabels: 'Result Screen Text & Labels',
      headlineTitle: 'Headline Title',
      playAgainBtn: 'Play Again Button',
      playAgainPlaceholder: 'PLAY AGAIN',
      resultStatsElements: 'Result Statistics & Elements',
      finalScore: 'Final Score',
      finalScoreDesc: 'Total brand points collected',
      timeElapsed: 'Time Elapsed',
      timeElapsedDesc: 'Active catching duration',
      catchAccuracy: 'Catch Accuracy',
      catchAccuracyDesc: 'Good items caught vs missed',
      eventLeaderboard: 'Event Leaderboard',
      eventLeaderboardDesc: 'Top ranking players list',
      playAgainBtnDesc: 'Replay game action trigger',
      movesCount: 'Moves Count',
      movesCountDesc: 'Total card flip attempts',
      pairsMatched: 'Pairs Matched',
      pairsMatchedDesc: 'Completed card pairs',
      accuracyRate: 'Accuracy Rate',
      accuracyRateDesc: 'Matching precision percentage',
      avgReactionTime: 'Average Reaction Time',
      avgReactionTimeDesc: 'Primary reflex benchmark metric',
      bestReaction: 'Best Reaction',
      bestReactionDesc: 'Fastest single round reflex',
      worstReaction: 'Worst Reaction',
      worstReactionDesc: 'Slowest reaction or penalty',
      roundResults: 'Round Results',
      roundResultsDesc: 'Individual 5-round reaction times',
      reactionTierRating: 'Reaction Tier Rating',
      reactionTierRatingDesc: 'Godlike, F1 Driver, Fast tier',
      addElement: 'Add Element',
      containers: 'Containers',
      visuals: 'Visuals',
      infoAndText: 'Info & Text',
      controls: 'Controls',
      undoTooltip: 'Undo (Ctrl+Z)',
      redoTooltip: 'Redo (Ctrl+Y)',
      alignLeftTooltip: 'Align Left',
      alignCenterHTooltip: 'Align Center Horizontally',
      alignRightTooltip: 'Align Right',
      alignTopTooltip: 'Align Top',
      alignCenterVTooltip: 'Align Center Vertically',
      alignBottomTooltip: 'Align Bottom',
      distributeHTooltip: 'Distribute Horizontally',
      distributeVTooltip: 'Distribute Vertically',
      centerHCanvas: 'Center Horizontally on Canvas',
      centerVCanvas: 'Center Vertically on Canvas',
      groupTooltip: 'Group Selected (Ctrl+G)',
      ungroupTooltip: 'Ungroup Selected (Ctrl+Shift+G)',
      bringToFront: 'Bring to Front',
      bringForward: 'Bring Forward',
      sendBackward: 'Send Backward',
      sendToBack: 'Send to Back',
      lockSelection: 'Lock Selection',
      unlockSelection: 'Unlock Selection',
      duplicateSelection: 'Duplicate (Ctrl+D)',
      deleteSelection: 'Delete (Del)',
      presetLibraryBtn: 'Preset Library',
      saveAsTemplateBtn: 'Save Template',
      togglePreviewTooltip: 'Toggle Live Interactive Preview',
      previewActive: 'Preview Active',
      preview: 'Preview',
      fullscreenTooltip: 'Fullscreen Editor',
      resetCanvasLayout: 'Reset Canvas Layout',
      closeEditor: 'Close Editor (Esc)',
      layersAndElements: 'Layers & Elements',
      filterLayers: 'Filter layers...',
      noLayersFound: 'No layers found',
      emptyCanvas: 'Empty Canvas',
      clickAddElement: 'Click "+ Add Element" to start building your screen.',
      propertyInspector: 'Property Inspector',
      noElementSelected: 'No Element Selected',
      selectElementToEdit: 'Click any element on canvas or layer tree to edit properties.',
      multipleElements: '{{count}} Elements Selected',
      editingMultipleDesc: 'Editing common properties across all selected items.',
      canvasDimensions: 'Canvas: {{width}} × {{height}} px',
      zoomLevel: 'Zoom: {{zoom}}%',
      resetZoomTooltip: 'Reset Zoom to 100%',
      zoomInTooltip: 'Zoom In (+)',
      zoomOutTooltip: 'Zoom Out (-)',
      fitToScreen: 'Fit to Screen',
      presetLibraryTitle: 'Start Screen Presets & Layouts',
      resultPresetLibraryTitle: 'Result Screen Presets & Layouts',
      presetLibrarySubtitle: 'Select a pre-designed layout preset to instantly configure your screen.',
      applyPresetConfirm: 'Apply Preset',
      saveTemplateTitle: 'Save as Custom Template',
      saveTemplateSubtitle: 'Save current screen layout and styles as a reusable template preset.',
      templateNameLabel: 'Template Name',
      templateNamePlaceholder: 'e.g. Minimalist Sponsor Banner',
      templateCategoryLabel: 'Category',
      templateDescLabel: 'Description (Optional)',
      templateDescPlaceholder: 'Brief notes on this preset style...',
      saveTemplateBtn: 'Save Template',
      savingTemplate: 'Saving Template...',
      templateSaved: 'Template saved successfully!',
    },
    zh: {
      startScreenBg: '开始画面背景',
      resultScreenBg: '结算画面背景',
      activeThemeBg: '当前主题背景',
      activeThemeBgDesc: '沿用当前主题的背景图',
      solidColor: '纯色背景',
      solidColorDesc: '自定义单色纯色画板',
      customImage: '自定义独立图片',
      customImageDesc: '独立上传封面专属背景插图',
      customColor: '自定义颜色',
      customStartBgLoaded: '已载入自定义封面背景',
      aspectRatio16_9: '推荐 16:9 画布比例（1024×576px 或更高）',
      replaceImage: '更换图片',
      supportsPngJpgWebp: '支持 PNG、JPG、WebP 格式（最大 10MB）',
      darkBackdropOverlay: '暗色遮罩不透明度',
      startElementVisibility: '开始画面元素显隐控制',
      headerLogoEyebrow: '顶部品牌角标 / Logo',
      headerLogoEyebrowDesc: '画面顶部的街机徽标或品牌 Logo',
      rulesCollectiblesCards: '游戏规则与收集道具卡',
      rulesCollectiblesCardsDesc: '显示得分目标 (+10) 与扣分障碍 (-10)',
      keyboardHintsPill: '键盘操作提示胶囊',
      keyboardHintsPillDesc: '展示方向键与 A/D 键位操作说明',
      leaderboardBtn: '排行榜快捷按钮',
      leaderboardBtnDesc: '直通活动积分排行的快捷入口',
      howToPlayBtn: '游戏玩法说明按钮',
      howToPlayBtnDesc: '底部的玩法规则帮助弹窗入口',
      gameHeaderIcon: '游戏头部主题图标',
      gameHeaderIconDesc: '顶部网格模式专属符号标识',
      gridDimensionsPill: '网格规格标签',
      pairsCountPill: '卡牌配对数标签',
      timerDurationPill: '倒计时时长标签',
      startingGantryIcon: '起跑发车灯架图标',
      startingGantryIconDesc: '顶部 F1 反应测试闪电标识',
      roundsCountPill: '测试轮次标签',
      gantryLightsPill: '灯组数量标签',
      activeAndReady: '已生效可用',
      dragAndDrop: '或拖拽文件至此',
      bgOverlayDimming: '背景暗色遮罩深浅',
      resultTextLabels: '结算画面文案与按钮',
      headlineTitle: '大标题主文案',
      playAgainBtn: '再玩一次按钮',
      playAgainPlaceholder: '再玩一次',
      resultStatsElements: '战绩结算卡片与数据项',
      finalScore: '最终得分',
      finalScoreDesc: '累计捕获的品牌有效积分',
      timeElapsed: '用时时长',
      timeElapsedDesc: '当局有效游戏耗时',
      catchAccuracy: '捕获命中率',
      catchAccuracyDesc: '有效道具捕获率 vs 遗漏率',
      eventLeaderboard: '活动现场排行榜',
      eventLeaderboardDesc: '现场高分榜单与玩家名次',
      playAgainBtnDesc: '触发重新开启一局的交互按钮',
      movesCount: '翻牌步数',
      movesCountDesc: '翻开卡牌尝试的总次数',
      pairsMatched: '成功配对数',
      pairsMatchedDesc: '已成功消除的卡牌对数',
      accuracyRate: '配对准确率',
      accuracyRateDesc: '有效翻牌命中占比',
      avgReactionTime: '平均反应时间',
      avgReactionTimeDesc: '多轮起跑核心综合反应指标',
      bestReaction: '最快单轮成绩',
      bestReactionDesc: '最佳单轮极速发车毫秒数',
      worstReaction: '最慢单轮成绩',
      worstReactionDesc: '最慢反应轮次或抢跑罚时',
      roundResults: '各轮反应明细',
      roundResultsDesc: '各单轮成绩明细与达标表现',
      reactionTierRating: '反应等级评定',
      reactionTierRatingDesc: '车神、职业车手、极速达人等评级',
      addElement: '添加元素',
      containers: '布局容器',
      visuals: '视觉与装饰',
      infoAndText: '信息与文案',
      controls: '交互控件',
      undoTooltip: '撤销 (Ctrl+Z)',
      redoTooltip: '重做 (Ctrl+Y)',
      alignLeftTooltip: '左对齐',
      alignCenterHTooltip: '水平居中对齐',
      alignRightTooltip: '右对齐',
      alignTopTooltip: '顶对齐',
      alignCenterVTooltip: '垂直居中对齐',
      alignBottomTooltip: '底对齐',
      distributeHTooltip: '水平等距分布',
      distributeVTooltip: '垂直等距分布',
      centerHCanvas: '在画布水平居中',
      centerVCanvas: '在画布垂直居中',
      groupTooltip: '编组选中项 (Ctrl+G)',
      ungroupTooltip: '解散编组 (Ctrl+Shift+G)',
      bringToFront: '置于顶层',
      bringForward: '上移一层',
      sendBackward: '下移一层',
      sendToBack: '置于底层',
      lockSelection: '锁定选中项',
      unlockSelection: '解锁选中项',
      duplicateSelection: '复制元素 (Ctrl+D)',
      deleteSelection: '删除元素 (Del)',
      presetLibraryBtn: '预设布局库',
      saveAsTemplateBtn: '存为模板',
      togglePreviewTooltip: '切换实时可交互预览',
      previewActive: '预览中',
      preview: '预览',
      fullscreenTooltip: '全屏编辑器',
      resetCanvasLayout: '重置画布布局',
      closeEditor: '退出编辑器 (Esc)',
      layersAndElements: '图层与元素层级',
      filterLayers: '过滤图层...',
      noLayersFound: '未找到匹配图层',
      emptyCanvas: '空白画布',
      clickAddElement: '点击“+ 添加元素”开始自由搭建画面。',
      propertyInspector: '属性检查面板',
      noElementSelected: '未选中任何元素',
      selectElementToEdit: '在画布或图层树中点击任意元素以调整其属性。',
      multipleElements: '已选中 {{count}} 个元素',
      editingMultipleDesc: '正在同时编辑所有选中元素的公用属性。',
      canvasDimensions: '画布规格：{{width}} × {{height}} 像素',
      zoomLevel: '缩放：{{zoom}}%',
      resetZoomTooltip: '重置缩放到 100%',
      zoomInTooltip: '放大 (+)',
      zoomOutTooltip: '缩小 (-)',
      fitToScreen: '自适应屏幕',
      presetLibraryTitle: '开始画面预设模板库',
      resultPresetLibraryTitle: '结算画面预设模板库',
      presetLibrarySubtitle: '选择精心设计的布局模板，一键套用并自动排版。',
      applyPresetConfirm: '应用此预设',
      saveTemplateTitle: '保存为自定义模板',
      saveTemplateSubtitle: '将当前屏幕的布局排版与视觉样式保存为可复用的专属模板。',
      templateNameLabel: '模板名称',
      templateNamePlaceholder: '例如：极简赞助商联名风、高对比度竞技风',
      templateCategoryLabel: '模板分类',
      templateDescLabel: '描述说明（可选）',
      templateDescPlaceholder: '关于此预设风格和适用场景的简要说明...',
      saveTemplateBtn: '确认保存模板',
      savingTemplate: '正在保存模板...',
      templateSaved: '模板保存成功！',
    },
    ms: {
      startScreenBg: 'Latar Belakang Skrin Mula',
      resultScreenBg: 'Latar Belakang Skrin Keputusan',
      activeThemeBg: 'Latar Belakang Tema Aktif',
      activeThemeBgDesc: 'Menggunakan kertas dinding tema',
      solidColor: 'Warna Pepejal',
      solidColorDesc: 'Warna latar belakang tersuai',
      customImage: 'Imej Tersuai',
      customImageDesc: 'Muat naik karya seni bebas',
      customColor: 'Warna Tersuai',
      customStartBgLoaded: 'Latar Belakang Skrin Mula Tersuai Dimuatkan',
      aspectRatio16_9: 'Nisbah aspek 16:9 disyorkan (1024×576px atau lebih tinggi)',
      replaceImage: 'Gantikan Imej',
      supportsPngJpgWebp: 'Menyokong PNG, JPG, WebP (Maks 10MB)',
      darkBackdropOverlay: 'Lapisan Tirai Gelap',
      startElementVisibility: 'Keterlihatan Elemen Skrin Mula',
      headerLogoEyebrow: 'Logo / Teks Atas Pengepala',
      headerLogoEyebrowDesc: 'Lencana arked atas atau logo jenama',
      rulesCollectiblesCards: 'Kad Peraturan & Koleksi',
      rulesCollectiblesCardsDesc: 'Menunjukkan sasaran (+10) dan bahaya (-10)',
      keyboardHintsPill: 'Petunjuk Papan Kekunci',
      keyboardHintsPillDesc: 'Menunjukkan kawalan Anak Panah & A/D',
      leaderboardBtn: 'Butang Papan Pendahulu',
      leaderboardBtnDesc: 'Pintasan ke skor',
      howToPlayBtn: 'Butang Panduan Cara Bermain',
      howToPlayBtnDesc: 'Butang modal bantuan di pengaki',
      gameHeaderIcon: 'Ikon Pengepala Permainan',
      gameHeaderIconDesc: 'Lencana simbol grid di bahagian atas',
      gridDimensionsPill: 'Dimensi Grid',
      pairsCountPill: 'Bilangan Pasangan Kad',
      timerDurationPill: 'Tempoh Pemasa',
      startingGantryIcon: 'Ikon Gantry Mula',
      startingGantryIconDesc: 'Simbol kilat refleks atas',
      roundsCountPill: 'Bilangan Pusingan',
      gantryLightsPill: 'Lampu Gantry',
      activeAndReady: 'Aktif & Sedia',
      dragAndDrop: 'atau seret dan lepas',
      bgOverlayDimming: 'Peredupan Tindanan Latar Belakang',
      resultTextLabels: 'Teks & Label Skrin Keputusan',
      headlineTitle: 'Tajuk Utama',
      playAgainBtn: 'Butang Main Semula',
      playAgainPlaceholder: 'MAIN SEMULA',
      resultStatsElements: 'Statistik & Elemen Keputusan',
      finalScore: 'Skor Akhir',
      finalScoreDesc: 'Jumlah mata jenama dikumpul',
      timeElapsed: 'Masa Berlalu',
      timeElapsedDesc: 'Tempoh tangkapan aktif',
      catchAccuracy: 'Ketepatan Tangkapan',
      catchAccuracyDesc: 'Item baik ditangkap vs terlepas',
      eventLeaderboard: 'Papan Pendahulu Acara',
      eventLeaderboardDesc: 'Senarai pemain kedudukan teratas',
      playAgainBtnDesc: 'Pencetus tindakan main semula permainan',
      movesCount: 'Bilangan Percubaan',
      movesCountDesc: 'Jumlah percubaan membalikkan kad',
      pairsMatched: 'Pasangan Dipadankan',
      pairsMatchedDesc: 'Pasangan kad yang selesai',
      accuracyRate: 'Kadar Ketepatan',
      accuracyRateDesc: 'Peratusan ketepatan padanan',
      avgReactionTime: 'Purata Masa Tindak Balas',
      avgReactionTimeDesc: 'Metrik penanda aras refleks utama',
      bestReaction: 'Tindak Balas Terbaik',
      bestReactionDesc: 'Refleks pusingan tunggal terpantas',
      worstReaction: 'Tindak Balas Terburuk',
      worstReactionDesc: 'Tindak balas paling perlahan atau penalti',
      roundResults: 'Keputusan Pusingan',
      roundResultsDesc: 'Masa tindak balas 5 pusingan individu',
      reactionTierRating: 'Penilaian Peringkat Tindak Balas',
      reactionTierRatingDesc: 'Peringkat Pemandu F1, Pantas, Cemerlang',
      addElement: 'Tambah Elemen',
      containers: 'Bekas',
      visuals: 'Visual',
      infoAndText: 'Maklumat & Teks',
      controls: 'Kawalan',
      undoTooltip: 'Buat Asal (Ctrl+Z)',
      redoTooltip: 'Buat Semula (Ctrl+Y)',
      alignLeftTooltip: 'Jajarkan ke Kiri',
      alignCenterHTooltip: 'Jajarkan Tengah Mendatar',
      alignRightTooltip: 'Jajarkan ke Kanan',
      alignTopTooltip: 'Jajarkan ke Atas',
      alignCenterVTooltip: 'Jajarkan Tengah Menegak',
      alignBottomTooltip: 'Jajarkan ke Bawah',
      distributeHTooltip: 'Agihkan Secara Mendatar',
      distributeVTooltip: 'Agihkan Secara Menegak',
      centerHCanvas: 'Tengahkan Mendatar pada Kanvas',
      centerVCanvas: 'Tengahkan Menegak pada Kanvas',
      groupTooltip: 'Kumpulkan Pilihan (Ctrl+G)',
      ungroupTooltip: 'Nyahkumpul Pilihan (Ctrl+Shift+G)',
      bringToFront: 'Bawa ke Hadapan Sekali',
      bringForward: 'Bawa ke Hadapan',
      sendBackward: 'Hantar ke Belakang',
      sendToBack: 'Hantar ke Belakang Sekali',
      lockSelection: 'Kunci Pilihan',
      unlockSelection: 'Buka Kunci Pilihan',
      duplicateSelection: 'Gandakan (Ctrl+D)',
      deleteSelection: 'Padam (Del)',
      presetLibraryBtn: 'Pustaka Pratetap',
      saveAsTemplateBtn: 'Simpan Templat',
      togglePreviewTooltip: 'Togol Pratonton Interaktif Langsung',
      previewActive: 'Pratonton Aktif',
      preview: 'Pratonton',
      fullscreenTooltip: 'Editor Skrin Penuh',
      resetCanvasLayout: 'Tetapkan Semula Susun Atur Kanvas',
      closeEditor: 'Tutup Editor (Esc)',
      layersAndElements: 'Lapisan & Elemen',
      filterLayers: 'Tapis lapisan...',
      noLayersFound: 'Tiada lapisan ditemui',
      emptyCanvas: 'Kanvas Kosong',
      clickAddElement: 'Klik "+ Tambah Elemen" untuk mula membina skrin anda.',
      propertyInspector: 'Pemeriksa Sifat',
      noElementSelected: 'Tiada Elemen Dipilih',
      selectElementToEdit: 'Klik mana-mana elemen pada kanvas atau pepohon lapisan untuk mengedit sifat.',
      multipleElements: '{{count}} Elemen Dipilih',
      editingMultipleDesc: 'Mengedit sifat sepunya merentas semua item yang dipilih.',
      canvasDimensions: 'Kanvas: {{width}} × {{height}} px',
      zoomLevel: 'Zum: {{zoom}}%',
      resetZoomTooltip: 'Tetapkan Semula Zum ke 100%',
      zoomInTooltip: 'Zum Masuk (+)',
      zoomOutTooltip: 'Zum Keluar (-)',
      fitToScreen: 'Muat ke Skrin',
      presetLibraryTitle: 'Pratetap & Susun Atur Skrin Mula',
      resultPresetLibraryTitle: 'Pratetap & Susun Atur Skrin Keputusan',
      presetLibrarySubtitle: 'Pilih pratetap susun atur pra-reka bentuk untuk mengkonfigurasi skrin anda serta-merta.',
      applyPresetConfirm: 'Gunakan Pratetap',
      saveTemplateTitle: 'Simpan sebagai Templat Tersuai',
      saveTemplateSubtitle: 'Simpan susun atur dan gaya skrin semasa sebagai pratetap templat yang boleh diguna semula.',
      templateNameLabel: 'Nama Templat',
      templateNamePlaceholder: 'cth. Sepanduk Penaja Minimalis',
      templateCategoryLabel: 'Kategori',
      templateDescLabel: 'Penerangan (Pilihan)',
      templateDescPlaceholder: 'Nota ringkas mengenai gaya pratetap ini...',
      saveTemplateBtn: 'Simpan Templat',
      savingTemplate: 'Sedang Menyimpan Templat...',
      templateSaved: 'Templat berjaya disimpan!',
    },
  },
};

function injectBundle(filePath: string, lang: 'en' | 'zh' | 'ms') {
  let content = fs.readFileSync(filePath, 'utf8');

  for (const [namespace, langBundle] of Object.entries(additions)) {
    const keys = langBundle[lang];
    if (!keys) continue;

    const nsHeader = `  ${namespace}: {`;
    const nsPos = content.indexOf(nsHeader);

    if (nsPos !== -1) {
      // Namespace exists: inject keys right after header
      const insertPos = nsPos + nsHeader.length;
      let newLines = '';
      for (const [k, v] of Object.entries(keys)) {
        const keyPattern = new RegExp(`\\b${k}\\s*:`);
        // Search within namespace up to end of namespace
        if (!keyPattern.test(content)) {
          const escaped = v.replace(/'/g, "\\'");
          newLines += `\n    ${k}: '${escaped}',`;
        }
      }
      if (newLines) {
        content = content.slice(0, insertPos) + newLines + content.slice(insertPos);
      }
    } else {
      // Namespace does not exist: append before closing `};`
      const endPos = content.lastIndexOf('};');
      if (endPos !== -1) {
        let block = `\n  ${namespace}: {\n`;
        for (const [k, v] of Object.entries(keys)) {
          const escaped = v.replace(/'/g, "\\'");
          block += `    ${k}: '${escaped}',\n`;
        }
        block += `  },\n`;
        content = content.slice(0, endPos) + block + content.slice(endPos);
      }
    }
  }

  fs.writeFileSync(filePath, content, 'utf8');
}

injectBundle(enPath, 'en');
injectBundle(zhPath, 'zh');
injectBundle(msPath, 'ms');
console.log('Final localization keys successfully injected into en, zh-CN, ms-MY.');
